### ISSUE TITLE
拉不到 360cloud/wayne镜像，是不是还没有上传？

### ISSUE THREAD

**Issue by hihunk** [Qihoo360/wayne#1]
https://hub.docker.com/r/360cloud/wayne/
![image](https://user-images.githubusercontent.com/15373077/48684679-c0400e00-ebed-11e8-80e7-834778738898.png)

```
docker pull 360cloud/wayne
Using default tag: latest
Error response from daemon: manifest for 360cloud/wayne:latest not found
```

**Comment by hihunk** [comment]
> 打个中文。

？

**Comment by 70data** [comment]
The mirror image is ready.
Please use command `docker pull 360cloud/wayne:latest`.
@hihunk

**Comment by wilhelmguo** [comment]
Image is ready. Please check with ```docker pull 360cloud/wayne:latest```

**Comment by hihunk** [comment]
赞
