### ISSUE TITLE
使用ldap用户登入后页面空白

### ISSUE THREAD

**Issue by purelind** [Qihoo360/wayne#105]
**Describe the bug**
按照wiki使用k8s部署的wayne，配置好了ldap设置，参照群里的建议设置ldap_scope=3。日志显示通过ldap成功登入，跳转到http://youip:NodePort/public/ 这个空白页面，使用admin账户登入将用户设置为管理员，再次使用该账户登入则页面显示正常
**To Reproduce**

**Expected behavior**

**Screenshots**
![wayne-bug1-screenshot_20181206_161137](https://user-images.githubusercontent.com/16618216/49570679-42f8f500-f972-11e8-8173-5b1010d8b9c5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian9
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] 63.0.3 (64-bit)

**Server Version**
```
- Dashboard version: v1.0.1
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by wilhelmguo** [comment]
Refer to https://github.com/Qihoo360/wayne/wiki/FAQ
MySQL5.7 报错 this is incompatible with sql_mode=only_full_group_by
