### ISSUE TITLE
Recator Frontend Code（Test by Ingress）

### ISSUE THREAD

**Issue by chengyumeng** [Qihoo360/wayne#116]
In the development of the front end of ingress, I found a lot of painful copy and paste. This meaningless work lasted for more than a week. In my eyes, there may be many problems with the code of many front-end pages.

For example, the same code is everywhere, many functions are named too casually (a behavior does not use verb naming, etc.), no planning and abstraction

In short, the TypeScript logic of the service page may not be much different from the logic of the ingress page, but when I write ingress, it actually takes four thousand lines of code, which is too painful!

So I decided to abstract some of the base classes and public functions, and I believe that after this transformation, our front-end code will become much more elegant.

Considering the huge amount of work, I will first define the base class and general logic, and then transform on the basis of ingress. This will be the first PR, the transformation of other pages, you can complete together!

**Comment by HZ89** [comment]
and the back-end code also have no abstraction.
