### ISSUE TITLE
注销登录，web会抖动一次，后端currentuser报错401

### ISSUE THREAD

**Issue by zhanghuidinah** [Qihoo360/wayne#12]
**Describe the bug**

**To Reproduce**
1. Go to '注销登录'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31201589/48706106-218bcf80-ec36-11e8-8691-3eb59c5f1d9e.png)

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by wilhelmguo** [comment]
目前就是这么设计的，根据http code 判断用户是否登录。
