### ISSUE TITLE
有没有计划通过平台进行k8s集群自动化部署

### ISSUE THREAD

**Issue by hadoop835** [Qihoo360/wayne#126]
有没有计划通过平台进行k8s集群自动化部署

**Comment by wilhelmguo** [comment]
@hadoop835 Wayne 定位是K8S发布平台，方便用户发布和管理K8S资源。
自动化部署K8S集群已经有很多成熟方案，推荐使用 https://github.com/kubernetes-sigs/kubespray 或者官方kubeadm
