### ISSUE TITLE
switch start_time or end_time to query online statistics, api/v1/publish/statistics报错400

### ISSUE THREAD

**Issue by zhanghuidinah** [Qihoo360/wayne#13]
**Describe the bug**

**To Reproduce**
1. Go to '上线次数统计'
2. Click on '更换start_time or end_time'

**Expected behavior**
- 可按所选时间范围查询上线次数统计
**Screenshots**
![image](https://user-images.githubusercontent.com/31201589/48706443-416fc300-ec37-11e8-8f8c-2caa016f2146.png)

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by wilhelmguo** [comment]
Fixed!
