### ISSUE TITLE
Migration Service from exist kubernetes clusters

### ISSUE THREAD

**Issue by wilhelmguo** [Qihoo360/wayne#132]
**Is your feature request related to a problem? Please describe.**

- Goto Admin-Kubernetes-Service
- Select one Service， click migration
- Select a existing App and Confirm template, click submit button
- Auto create Service and Template on selected App.
- Go to Portal deploy the template

Refer to Deployment
![image](https://user-images.githubusercontent.com/12826425/49853078-fe150880-fe20-11e8-930b-0b28eb99cb48.png)

**Comment by HZ89** [comment]
#170
