### ISSUE TITLE
Migration Ingress from exist kubernetes clusters

### ISSUE THREAD

**Issue by wilhelmguo** [Qihoo360/wayne#135]
**Is your feature request related to a problem? Please describe.**
- Goto Admin-Kubernetes-Ingress
- Select one Ingress， click migration
- Select a existing App and Confirm template, click submit button
- Auto create Ingress and Template on selected App.
- Go to Portal deploy the template

Refer to Deployment
![image](https://user-images.githubusercontent.com/12826425/49853078-fe150880-fe20-11e8-930b-0b28eb99cb48.png)

**Comment by HZ89** [comment]
#169
