### ISSUE TITLE
MySQL5.6建库问题

### ISSUE THREAD

**Issue by mojie126** [Qihoo360/wayne#143]
由于MySQL5.6不支持默认row_format=dynamic，从镜像部署时，建表语句也没有使用ROW_FORMAT=DYNAMIC

那么...只能手动建表了么...？

**Comment by wilhelmguo** [comment]
@mojie126 https://github.com/Qihoo360/wayne/wiki/Wayne-dev-deploy 参考手动数据库初始化流程
