### ISSUE TITLE
支持Endpoint

### ISSUE THREAD

**Issue by 846677234** [Qihoo360/wayne#146]
**Describe the solution you'd like**
有些外部服务需要映射进来，则需要创建Endpoint，希望支持

**Comment by wilhelmguo** [comment]
@846677234 无法使用Service的 ExternalName么？

**Comment by 846677234** [comment]
@wilhelmguo ExternalName不支持设置端口，有些场景支持不了

**Comment by wilhelmguo** [comment]
@846677234 后续会支持Kubernetes所有资源管理，但目前来说Endpoint优先级不高，如果有想法的话可以提PR

**Comment by wilhelmguo** [comment]
@846677234 endpoint latest 版本已经支持，下一版本会包含该feature
