### ISSUE TITLE
Ordinary users cannot see Ingress resources

### ISSUE THREAD

**Issue by wilhelmguo** [Qihoo360/wayne#147]
**Describe the bug**
Ordinary users cannot see Ingress resources

**To Reproduce**
1. Go to 'App detail '
2. Click on 'add user to App'
3.  No Ingress resource

![image](https://user-images.githubusercontent.com/12826425/49986263-24b27b00-ffaa-11e8-9f89-eb476b9aa9b8.png)

**Comment by chengyumeng** [comment]
Maybe you should add permission to your non-admin users？
Re： https://github.com/Qihoo360/wayne/wiki/Wayne-dev-permission#ingress

**Comment by wilhelmguo** [comment]
@chengyumeng No new permissions added
