### ISSUE TITLE
Configurable max limit/request ratio

### ISSUE THREAD

**Issue by alex-lx** [Qihoo360/wayne#157]
**Is your feature request related to a problem? Please describe.**
it seems Wayne force config request as 0.5 * limit.

**Describe the solution you'd like**
A config to specify the max radio.

**Describe alternatives you've considered**

**Additional context**

**Comment by wilhelmguo** [comment]
@alex-lx  Refer to https://github.com/Qihoo360/wayne/wiki/Wayne-admin-deployment

**Comment by alex-lx** [comment]
@wilhelmguo Thanks. But is there any way to modify the default value? bacause we have 60 statefulsets in our cluster...

**Comment by wilhelmguo** [comment]
@alex-lx There is currently no global configuration, and then I will consider increasing the global configuration just like environment variables.

**Comment by wilhelmguo** [comment]
Or Do you have time to implement a PR add global configuration with reference to the env configuration?
