### ISSUE TITLE
服务启动时，报没有数据库（已解决）

### ISSUE THREAD

**Issue by hihunk** [Qihoo360/wayne#16]
>已解决：
刚看了一下代码，试了一下，这是因为初始化数据库是从创建数据库开始的。
自己自己之前创建了这个同名数据库导致的初始化数据库部分没有执行。
把同名数据库删掉，或在配置文件中换个名字。就OK了。

**Describe the bug**
服务启动时，报没有数据库
![image](https://user-images.githubusercontent.com/15373077/48748631-72d9a480-ecb2-11e8-831f-ca77a603c431.png)
下代码看了一下，初台化数据库的代码被注释了？
![image](https://user-images.githubusercontent.com/15373077/48748676-969cea80-ecb2-11e8-8da5-31ee3d447655.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by cx2c** [comment]
+1

**Comment by hihunk** [comment]
> +1

刚看了一下代码，试了一下，这是因为初始化数据库是从创建数据库开始的。
自己自己之前创建了这个同名数据库导致的初始化数据库部分没有执行。
把同名数据库删掉，或在配置文件中换个名字。就OK了。

**Comment by muyu66** [comment]
+1
建议REAMD.md标注一下

**Comment by wilhelmguo** [comment]
@hihunk @muyu66 @cx2c 建议按照官方文档一步步进行安装，文档中已经写明。
![image](https://user-images.githubusercontent.com/12826425/55694446-d3117e80-59e6-11e9-93e1-35d611564b98.png)
 https://360yun.org/wayne/summary/deploy.html

**Comment by muyu66** [comment]
> @hihunk @muyu66 @cx2c 建议按照官方文档一步步进行安装，文档中已经写明。
> ![image](https://user-images.githubusercontent.com/12826425/55694446-d3117e80-59e6-11e9-93e1-35d611564b98.png)
> https://360yun.org/wayne/summary/deploy.html


我家宽带好像是dns问题，无法访问360yun。所以当时就没看，以为README.md是足够的
