### ISSUE TITLE
启动了访问后台没有登录页面

### ISSUE THREAD

**Issue by firehalt** [Qihoo360/wayne#162]
已经启动成功，但是我访问后台登陆页面不出来东西
![image](https://user-images.githubusercontent.com/29405113/50203726-6de53f00-039d-11e9-8679-3e874754e924.png)

报错信息
 
![image](https://user-images.githubusercontent.com/29405113/50203757-848b9600-039d-11e9-8b4b-a8812d84bced.png)

数据库里面也没有数据
![image](https://user-images.githubusercontent.com/29405113/50203803-abe26300-039d-11e9-9fc3-b6fecfaeecca.png)

**Comment by wilhelmguo** [comment]
@firehalt  请按照安装文档执行初始化，不要手动创建数据库。 https://github.com/Qihoo360/wayne/wiki/Wayne-dev-deploy
