### ISSUE TITLE
在k8s中启动报错

### ISSUE THREAD

**Issue by liyongzhezz** [Qihoo360/wayne#17]
`kubectl create -f hack/kubernetes`
执行上边的命令创建项目后，infra-wayne这个pod启动失败并有如下错误：

>[ORM]2018/11/20 10:58:03 unsupport orm tag int
[ORM]2018/11/20 10:58:03 unsupport orm tag bool
[ORM]2018/11/20 10:58:03 unsupport orm tag int
[ORM]2018/11/20 10:58:03 unsupport orm tag bool
[ORM]2018/11/20 10:58:03 register db Ping `default`, invalid DSN: did you forget to escape a param value?
panic: register db Ping `default`, invalid DSN: did you forget to escape a param value?
>
>goroutine 1 [running]:
github.com/Qihoo360/wayne/src/backend/initial.InitDb()
	/go/src/github.com/Qihoo360/wayne/src/backend/initial/db.go:25 +0x161
github.com/Qihoo360/wayne/src/backend/cmd/apiserver.run(0x1e43880, 0x1e704a0, 0x0, 0x0)
	/go/src/github.com/Qihoo360/wayne/src/backend/cmd/apiserver/apiserver.go:23 +0x26
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).execute(0x1e43880, 0x1e704a0, 0x0, 0x0, 0x1e43880, 0x1e704a0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1e433c0, 0x0, 0x1e43620, 0x1e43ae0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).Execute(0x1e433c0, 0xc4206c9f78, 0xc4200a4058)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/Qihoo360/wayne/src/backend/main.go:12 +0x53

configmap配置如下：

```apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: infra-wayne
  name: infra-wayne
  namespace: default
data:
  app.conf: |-
    appname = wayne
    httpport = 8080
    runmode = prod
    autorender = false
    copyrequestbody = true
    StaticDir = public:static
    EnableDocs = true
    EnableAdmin = true
    DBName = wayne
    DBTns = tcp(10.10.99.225:3306)
    DBUser = root
    DBPasswd = root
```

**Comment by decker502** [comment]
me too

**Comment by dotw** [comment]
the same issue

**Comment by decker502** [comment]
查看了源码，配置文件需要修改：
```
１.  hack/kubernetes/deployment.yaml
....
        volumeMounts:
        - mountPath: /opt/wayne/conf/dev.conf
          name: config
          subPath: dev.conf
      volumes:
      - name: config
        configMap:
          name: infra-wayne

2. hack/kubernetes/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: infra-wayne
  name: infra-wayne
  namespace: wayne
data:
  dev.conf: |-
    appname = wayne
    httpport = 8080
    runmode = prod
    autorender = false
    copyrequestbody = true
    StaticDir = public:static
    EnableDocs = true
    EnableAdmin = true
    ShowSql = true
    DBTns = tcp(192.168.1.204:3306)
    DBName = wayne
    DBUser = wayne
    DBPasswd = wayne
 
# ... add your config
```

**Comment by xzyeah** [comment]
> 查看了源码，配置文件需要修改：
> 
> ```
> １.  hack/kubernetes/deployment.yaml
> ....
>         volumeMounts:
>         - mountPath: /opt/wayne/conf/dev.conf
>           name: config
>           subPath: dev.conf
>       volumes:
>       - name: config
>         configMap:
>           name: infra-wayne
> 
> 2. hack/kubernetes/configmap.yaml
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   labels:
>     app: infra-wayne
>   name: infra-wayne
>   namespace: wayne
> data:
>   dev.conf: |-
>     appname = wayne
>     httpport = 8080
>     runmode = prod
>     autorender = false
>     copyrequestbody = true
>     StaticDir = public:static
>     EnableDocs = true
>     EnableAdmin = true
>     ShowSql = true
>     DBTns = tcp(192.168.1.204:3306)
>     DBName = wayne
>     DBUser = wayne
>     DBPasswd = wayne
>  
> # ... add your config
> ```

这样就可以吗？

我的是报

> [ORM]2018/11/20 15:55:00 unsupport orm tag bool
panic: parsing "": invalid syntax
 goroutine 1 [running]:
github.com/Qihoo360/wayne/src/backend/cmd/apiserver.run(0x1e43880, 0x1e704a0, 0x0, 0x0)
	/go/src/github.com/Qihoo360/wayne/src/backend/cmd/apiserver/apiserver.go:40 +0x14c
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).execute(0x1e43880, 0x1e704a0, 0x0, 0x0, 0x1e43880, 0x1e704a0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1e433c0, 0x0, 0x1e43620, 0x1e43ae0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).Execute(0x1e433c0, 0xc420711f78, 0xc4200c0058)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/Qihoo360/wayne/src/backend/main.go:12 +0x53

**Comment by wilhelmguo** [comment]
@xzyeah  需要配置app.conf 中所有配置

**Comment by zhanghuidinah** [comment]
- Please set up MySQL image or local MySQL and modify src/backend/conf/app.conf according to actual database configuration.To ensure the stable connection to MySQL.
![image](https://user-images.githubusercontent.com/31201589/48772562-bad2e880-ecff-11e8-99fc-464eeaa13af0.png)
- In addition, as the network switches IP will change.

**Comment by liyongzhezz** [comment]
本地安装的mysql，已经配置app.conf
```
## mysql
DBName = "${DB_NAME||wayne}"
DBTns = "${DB_TNS||tcp(10.10.99.225:3306)}"
DBUser = "${DB_USER||root}"
DBPasswd = "${DB_PASSWD||root}"
DBLoc = "${DB_LOC||Asia%2FShanghai}"
DBConnTTL = 30
```
并没有生效

```
[root@k8s-master kubernetes]# kubectl get pod  | grep wayne
infra-wayne-5564595b98-hnt2j   0/1       ContainerCreating   0          11s
infra-wayne-5564595b98-vxqpl   0/1       Error               0          12s
[root@k8s-master kubernetes]# kubectl get pod  | grep wayne
infra-wayne-5564595b98-hnt2j   0/1       ContainerCreating   0          12s
infra-wayne-5564595b98-vxqpl   0/1       Error               0          13s
[root@k8s-master kubernetes]# kubectl logs infra-wayne-5564595b98-vxqpl
[ORM]2018/11/20 20:14:06 unsupport orm tag int
[ORM]2018/11/20 20:14:06 unsupport orm tag bool
[ORM]2018/11/20 20:14:06 unsupport orm tag int
[ORM]2018/11/20 20:14:06 unsupport orm tag bool
panic: parsing "": invalid syntax

goroutine 1 [running]:
github.com/Qihoo360/wayne/src/backend/cmd/apiserver.run(0x1e43880, 0x1e704a0, 0x0, 0x0)
	/go/src/github.com/Qihoo360/wayne/src/backend/cmd/apiserver/apiserver.go:40 +0x14c
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).execute(0x1e43880, 0x1e704a0, 0x0, 0x0, 0x1e43880, 0x1e704a0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1e433c0, 0x0, 0x1e43620, 0x1e43ae0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).Execute(0x1e433c0, 0xc4206e9f78, 0xc4200a4058)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/Qihoo360/wayne/src/backend/main.go:12 +0x53
```

**Comment by dotw** [comment]
@decker502 it works

**Comment by wilhelmguo** [comment]
refer to https://github.com/Qihoo360/wayne/wiki/Wayne-dev-deploy
