### ISSUE TITLE
在前台界面，选择“部门概览”，再选择“上线记录”会报错

### ISSUE THREAD

**Issue by chengyh2golang** [Qihoo360/wayne#19]
**点击前台界面的“上线记录”，报错**

**操作步骤**
1. 进入前台界面
2. 点击“部门概览”
3. 选择“上线记录”
4. 提示报错，报错信息如下：
 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'wayne.a.create_time' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by 70data** [comment]
This is a problem with the use of MySQL 5.7.
@wilhelmguo

**Comment by 70data** [comment]
Please see the FAQ.
https://github.com/Qihoo360/wayne/wiki/FAQ
@chengyh2golang
