### ISSUE TITLE
创建部署时，页面卡死不动

### ISSUE THREAD

**Issue by ilanni2460** [Qihoo360/wayne#190]
创建部署时，页面卡死不动
![1](https://user-images.githubusercontent.com/5058391/50504403-65c98580-0aa8-11e9-8b3e-4dbdcef2d4e3.png)

**Comment by weixiao122** [comment]
我也遇到这个问题，请问应该怎么解决呢，或者怎么排查问题呢

**Comment by wilhelmguo** [comment]
请在前台创建部署
