### ISSUE TITLE
When different namespace/department name , same App name , same Deployment name , Can not create Deployment 

### ISSUE THREAD

**Issue by daigong** [Qihoo360/wayne#195]
**Describe the bug**
When different Deployment name , same App name , same Deployment name , Can not create Deployment 

在不同部门名称，相同项目，相同部署名称时，无法创建部署，错误信息： Resources already exist!  

**To Reproduce**
1. Go to Admin 
进入管理员界面
2. Create two namespace : test-1 , test-2 
创建两个空间
3. Create two same name app in different namespace : 
test-app in test-1 、test-app in test-2
在非admin页面中分别在两个部门下创建相同名称的app：test-app
4. Create two same name Deployment in test-1/test-app 、 test-2/test-app/deploy-test
在非admin页面中中分别在两个部门下的test-app中创建相同名字应用:deploy-test
4. See error：
错误：Resources already exist! 

**Expected behavior**

Create success

成功创建

**Desktop (please complete the following information):**
 - OS: Mac 10.14
 - Browser chrome

**Additional context**
deployment的全局唯一性好像是由 ${app}-${deployment}决定的，那namespace是不是就浪费了

**wayne version**
v1.2.2

好像helm也有同样的问题，用起来都很不方便

**Comment by daigong** [comment]
mysql> desc deployment;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | bigint(20)   | NO   | PRI | NULL    | auto_increment |
| name        | varchar(128) | NO   | UNI |         |                |
| meta_data   | longtext     | NO   |     | NULL    |                |
| app_id      | bigint(20)   | NO   | MUL | NULL    |                |
| description | varchar(512) | YES  |     | NULL    |                |
| order_id    | bigint(20)   | NO   | MUL | 0       |                |
| create_time | datetime     | NO   |     | NULL    |                |
| update_time | datetime     | NO   |     | NULL    |                |
| user        | varchar(128) | NO   |     |         |                |
| deleted     | tinyint(1)   | NO   |     | 0       |                |
+-------------+--------------+------+-----+---------+----------------+

我查看了下表结构，name 字段是 UNI ，是否可以考虑取消 name字段唯一，使用 name 和 app_id 唯一作为判断？对全局会不会有什么影响？

**Comment by wilhelmguo** [comment]
@daigong 目前Wayne的ns 和 k8s的ns是多对一的关系，即多个Wayne的ns可以对应一个K8S的ns，例如Wayne的ns default 和 test 都对应了 K8S的 default ns。如果不保证 deployment 名称全局唯一的话可能会出现同一个K8S ns 下deployment重名

**Comment by daigong** [comment]
收到，主要是 K8S 中好多命名有长度限制，哎，东西太多放不进去 😭 

从设计理念上  wayne ns 是用来隔离 组织中 行政级别  部门的概念，项目 从属于部门内部

我这么理解对么？
