### ISSUE TITLE
部门-项目-负载均衡-负载均衡模板中 ports 名字无法自定义，如果使用 istio，service名字期待 http-* grpc-* 等

### ISSUE THREAD

**Issue by daigong** [Qihoo360/wayne#201]
**Is your feature request related to a problem? Please describe.**
如果k8s集群中使用Istio，负载均衡 service命名期待规则 http-* grpc-*，但是wayne系统中service名字自动生成，而且服务修改

**Describe the solution you'd like**
页面提供修改service port 名字的input，默认显示自动生成的即可，如果可以，可以选择增加一个选项 http/ grpc /http2等作为前缀

**Comment by wilhelmguo** [comment]
@daigong Istio要求service的portname 必须按照一定的规则吗？是否提供下相关文档？

**Comment by daigong** [comment]
@wilhelmguo

Istio 使用service port name作为协议判断，不符合规则都被视为 tcp ，一些功能和监控指标都看不到，所以建议能够自定义 service port name

参见Istio文档：
https://istio.io/docs/setup/kubernetes/spec-requirements/
https://istio.io/zh/docs/setup/kubernetes/spec-requirements/

**Comment by wilhelmguo** [comment]
@daigong 感谢反馈，请在Wayne主项目也提交个PR，修改下 src/frontend/lib 引用的git版本号

**Comment by daigong** [comment]
@wilhelmguo 
已经提交 #202 

不过有个小疑问，为啥只有service 在 submodule ？😃
