### ISSUE TITLE
ingress服务的点击“对比模板”按钮没有反应

### ISSUE THREAD

**Issue by yannuo0802** [Qihoo360/wayne#205]
**Describe the bug**
在ingress服务中，点击“对比模板”按钮，没有任何反应，不知道是不是该模块的对比功能没有实现？
![image](https://user-images.githubusercontent.com/46117743/50806836-544b6d80-1333-11e9-84b6-8b3a2d6cb758.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by chengyumeng** [comment]
在我本地没有发现这个问题，你可以打开浏览器控制台看下什么报错么

**Comment by chengyumeng** [comment]
贴一下 Console 的报错

**Comment by yannuo0802** [comment]
本地debug模式下，控制台没有任何输出，我想问一下，上周提交的ingress路由修改代码，除了添加注解，别的地方还有修改吗？我只是在controller.ingress下添加了注解

**Comment by yannuo0802** [comment]
已经解决了，是ingress.component.html文件中33行里的click按钮方法引错方法了，引的是pvc里ts模块的diffTmp()方法.
解决：
改成ingress.component.ts里的161行的diffTpl()方法
