### ISSUE TITLE
前台删除 PVC 时，如果没有勾选 PVC 模板，就会跳转404页面，并把该项目下的所有 PVC 模板全部删除

### ISSUE THREAD

**Issue by yannuo0802** [Qihoo360/wayne#206]
**Describe the bug**
前台删除PCV时，如果没有勾选pvc模板，就会跳转404页面，并把该项目下的所有pvc模板全部删除
![image](https://user-images.githubusercontent.com/46117743/50807041-10a53380-1334-11e9-8965-0cef51a739af.png)
点击后会跳转404页面
![image](https://user-images.githubusercontent.com/46117743/50807123-3af6f100-1334-11e9-80d1-9cc2a568732b.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by chengyumeng** [comment]
@kofj

**Comment by yannuo0802** [comment]
@chengyumeng 这个问题是angularjs 配置的路由问题导致的，需要修改wayne\src\frontend\src\app\portal\persistentvolumeclaim\persistentvolumeclaim.component.ts文件72行，的
![image](https://user-images.githubusercontent.com/46117743/50819625-9097c180-1365-11e9-8654-2d3d4db96ae6.png)
修改后为
![image](https://user-images.githubusercontent.com/46117743/50819657-ad33f980-1365-11e9-9ae7-8a5b83dff248.png)
解决！！！

**Comment by kofj** [comment]
@BennieMeng

**Comment by BennieMeng** [comment]
@yannuo0802 it works, thanks very much! smile~
