### ISSUE TITLE
平台概览 机器数量中的数字按钮点进去后只显示第一个机群的节点 bug

### ISSUE THREAD

**Issue by istioo** [Qihoo360/wayne#21]
后台首页  系统报表   平台概览

机器数量中的数字按钮点进去后只显示第一个机群的节点，期望显示所有机群节点！

![default](https://user-images.githubusercontent.com/44183413/48754012-2babdd80-eccb-11e8-8909-3fb11c1f3704.png)

![default](https://user-images.githubusercontent.com/44183413/48754118-7fb6c200-eccb-11e8-8763-d0ae2932e990.png)

![default](https://user-images.githubusercontent.com/44183413/48754157-9fe68100-eccb-11e8-89f0-9ec1df4af0a5.png)

**Comment by chengyumeng** [comment]
On the node page,you can click the selector at the bottom right corner of this page to change cluster

**Comment by istioo** [comment]
3Q
