### ISSUE TITLE
对Ingress,service 和pvc 增加自定义注解

### ISSUE THREAD

**Issue by iyacontrol** [Qihoo360/wayne#221]
**Is your feature request related to a problem? Please describe.**
需要对Ingress,service 和pvc 增加自定义注解，便于wayne在公有云上的k8s更好使用。
**Describe the solution you'd like**
在页面创建以上三种资源对象的时候，支持自定义

**Comment by wangycc** [comment]
deployment和statefulset等等所有资源都建议添加annotation

**Comment by iyacontrol** [comment]
@wangycc deploy 和sts 其实加注解的场景在哪里？

**Comment by wangycc** [comment]
@iyacontrol 比如需要自动为deployment或者statefulset资源每个pod注入sidecar

pod需求: annotation来控制日志采集的service discover；对于没有service的pod需要annotation来控制Prometheus 的service discover； annotation来控制配置文件更新pod重启等等

**Comment by iyacontrol** [comment]
@wangycc 实际使用中，不建议直接起pod。应该将pod 被deploy等资源管理。一般比如想给pod 加注解，我一般使用是如下：

kind: Deployment
apiVersion: apps/v1
metadata:
  name: cmdb-gateway
  namespace: sgt
  labels:
    app: cmdb-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cmdb-gateway
  template:
    metadata:
      labels:
        app: cmdb-gateway
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/stats/prometheus'
        prometheus.io/port: '9000'


在template 里设置。

不知道是否和你的场景是一样的？

**Comment by wangycc** [comment]
@iyacontrol 你这里Prometheus SD用的就是pod资源的annotations

**Comment by 70data** [comment]
see this https://github.com/Qihoo360/wayne/issues/406.
