### ISSUE TITLE
建议后台管理增加对前台界面的管理 添加子菜单等功能？

### ISSUE THREAD

**Issue by iver3on** [Qihoo360/wayne#222]
1、建议后台管理增加对前台的管理 添加子菜单等功能？
2、我使用Kubernetes方式部署的，如何加入企业ldap
3、kubernetes方式不支持 Ui自定义？如何修改UI 
4、deployment 界面看不到 pod信息。。但是集群界面可以看到Node信息

**Comment by wilhelmguo** [comment]
@iver3on 可以详细描述一下你的需求么？ 如果有更多疑问可以进我们的官方群详细讨论下

**Comment by iver3on** [comment]
@wilhelmguo   
1、建议后台管理增加对前台UI的管理 添加子菜单等功能？
2、kubernetes方式不支持 Ui自定义？如何修改UI

**Comment by iver3on** [comment]
@wilhelmguo 
我使用Kubernetes方式部署的，如何加入企业ldap登录
deployment 界面看不到 pod信息。。但是集群界面可以看到Node信息  什么原因

**Comment by wilhelmguo** [comment]
> @wilhelmguo
> 1、建议后台管理增加对前台UI的管理 添加子菜单等功能？
> 2、kubernetes方式不支持 Ui自定义？如何修改UI

添加子菜单是什么意思？前台UI的资源都是Wayne的资源，发布时才会转化成kubernetes资源。建议先完整看下Waybe设计。

**Comment by wilhelmguo** [comment]
> @wilhelmguo
> 我使用Kubernetes方式部署的，如何加入企业ldap登录
> deployment 界面看不到 pod信息。。但是集群界面可以看到Node信息 什么原因

waybe本身就支持ldap配置，详细配置见 [https://github.com/Qihoo360/wayne/wiki/Wayne-dev-configuration](url)

Pod 资源正在支持中

**Comment by wilhelmguo** [comment]
@iver3on Pod 资源已经支持，谢谢
