### ISSUE TITLE
后台管理中的负载均衡和ingress列表，点击“名称”和“项目”全部跳转404页面?

### ISSUE THREAD

**Issue by yannuo0802** [Qihoo360/wayne#224]
**Describe the bug**
后台管理中的**负载均衡和ingress**列表，点击“名称”和“项目”全部跳转404页面?
![image](https://user-images.githubusercontent.com/46117743/51094183-c1ed1300-17e5-11e9-8eba-eba856a7609e.png)

**Comment by chengyumeng** [comment]
已修复
