### ISSUE TITLE
看不到Pod呢？？

### ISSUE THREAD

**Issue by iver3on** [Qihoo360/wayne#227]
你们提供的bee 没找到bin啊？
![image](https://user-images.githubusercontent.com/12184988/51095530-670ce900-17f0-11e9-962a-15c6b3df7cf5.png)

deployment界面看不到Pod呢？？
![image](https://user-images.githubusercontent.com/12184988/51095574-ba7f3700-17f0-11e9-94d8-3775e5274d95.png)

**Comment by wilhelmguo** [comment]
@iver3on Pod 资源正在支持中。
