### ISSUE TITLE
创建apikeys，角色一栏仅显示api类型的

### ISSUE THREAD

**Issue by yuexue0** [Qihoo360/wayne#257]
调用openapi方式操作，首先获取apikey，有些接口指明需要app类型的apikey。
但是在“角色”栏下拉列表中只显示了api类型数据。
![ee83ff6e-dc86-48e1-92a6-bb2664c6994a](https://user-images.githubusercontent.com/11746809/52617026-6a6dc000-2ed5-11e9-9e59-54d4227b4b26.png)

**Comment by chengyumeng** [comment]
你描述的问题比较混轮，角色下拉框显示的是已创建的角色，和 类型 是两码事。
