### ISSUE TITLE
有计划支持job吗?

### ISSUE THREAD

**Issue by vTNT** [Qihoo360/wayne#267]
RT

**Comment by wilhelmguo** [comment]
@vTNT 是指 Wayne 资源支持Job ，还是后台Kubernetes资源管理支持Job  ？

**Comment by vTNT** [comment]
Wayne 资源支持Job

**Comment by vTNT** [comment]
https://github.com/helm/charts/blob/master/stable/kong/templates/migrations-pre-upgrade.yaml
实现类似这种 创建个 kind: job

**Comment by wilhelmguo** [comment]
@vTNT 后期会支持，但目前来说优先级不高

**Comment by vTNT** [comment]
ok, xiexie
