### ISSUE TITLE
在国内浏览器中打不开

### ISSUE THREAD

**Issue by lizhiwei123** [Qihoo360/wayne#299]
部署wayne后，打开浏览器一直在加载页面，提示vender.js和mainjs加载不到，国内网路如何解决

**Comment by wilhelmguo** [comment]
@lizhiwei123 请详细描述部署环境和浏览器环境

**Comment by lizhiwei123** [comment]
> @lizhiwei123 请详细描述部署环境和浏览器环境

我部署在国内阿里云服务器上面的，端口都可以打开，然后通过网络访问部署好的服务，http://47.100.211.22:8080/，一直停留在loading界面，打开F12，提示vender.js和mainjs加载不到

**Comment by wilhelmguo** [comment]
@lizhiwei123 你这样描述无法定位具体问题，加微信群详细描述下吧

**Comment by lizhiwei123** [comment]
@wilhelmguo
好的，我的微信是18119157421，您加我一下吧

**Comment by wilhelmguo** [comment]
@lizhiwei123 https://github.com/Qihoo360/wayne/wiki  这里有开发者微信，加微信进群即可
