### ISSUE TITLE
panic: dial tcp 127.0.0.1:3306: connect: connection refused

### ISSUE THREAD

**Issue by SQGE** [Qihoo360/wayne#3]
[root@kube-m1 kubernetes]# kubectl logs -f infra-wayne-6d55fcf578-wknk6 wayne 
[ORM]2018/11/19 14:35:49 unsupport orm tag int
[ORM]2018/11/19 14:35:49 unsupport orm tag bool
[ORM]2018/11/19 14:35:49 unsupport orm tag int
[ORM]2018/11/19 14:35:49 unsupport orm tag bool
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
github.com/Qihoo360/wayne/src/backend/initial.InitDb()
	/go/src/github.com/Qihoo360/wayne/src/backend/initial/db.go:25 +0x161
github.com/Qihoo360/wayne/src/backend/cmd/apiserver.run(0x1e43880, 0x1e704a0, 0x0, 0x0)
	/go/src/github.com/Qihoo360/wayne/src/backend/cmd/apiserver/apiserver.go:23 +0x26
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).execute(0x1e43880, 0x1e704a0, 0x0, 0x0, 0x1e43880, 0x1e704a0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1e433c0, 0x0, 0x1e43620, 0x1e43ae0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).Execute(0x1e433c0, 0xc4206d5f78, 0xc4200a4058)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/Qihoo360/wayne/src/backend/main.go:12 +0x53
[root@kube-m1 kubernetes]# kubectl logs -f infra-wayne-6d55fcf578-wknk6 
[ORM]2018/11/19 14:35:49 unsupport orm tag int
[ORM]2018/11/19 14:35:49 unsupport orm tag bool
[ORM]2018/11/19 14:35:49 unsupport orm tag int
[ORM]2018/11/19 14:35:49 unsupport orm tag bool
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
github.com/Qihoo360/wayne/src/backend/initial.InitDb()
	/go/src/github.com/Qihoo360/wayne/src/backend/initial/db.go:25 +0x161
github.com/Qihoo360/wayne/src/backend/cmd/apiserver.run(0x1e43880, 0x1e704a0, 0x0, 0x0)
	/go/src/github.com/Qihoo360/wayne/src/backend/cmd/apiserver/apiserver.go:23 +0x26
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).execute(0x1e43880, 0x1e704a0, 0x0, 0x0, 0x1e43880, 0x1e704a0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1e433c0, 0x0, 0x1e43620, 0x1e43ae0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).Execute(0x1e433c0, 0xc4206d5f78, 0xc4200a4058)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/Qihoo360/wayne/src/backend/main.go:12 +0x53
[root@kube-m1 kubernetes]# kubectl logs -f infra-wayne-6d55fcf578-wknk6 
[ORM]2018/11/19 14:35:49 unsupport orm tag int
[ORM]2018/11/19 14:35:49 unsupport orm tag bool
[ORM]2018/11/19 14:35:49 unsupport orm tag int
[ORM]2018/11/19 14:35:49 unsupport orm tag bool
panic: dial tcp 127.0.0.1:3306: connect: connection refused

goroutine 1 [running]:
github.com/Qihoo360/wayne/src/backend/initial.InitDb()
	/go/src/github.com/Qihoo360/wayne/src/backend/initial/db.go:25 +0x161
github.com/Qihoo360/wayne/src/backend/cmd/apiserver.run(0x1e43880, 0x1e704a0, 0x0, 0x0)
	/go/src/github.com/Qihoo360/wayne/src/backend/cmd/apiserver/apiserver.go:23 +0x26
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).execute(0x1e43880, 0x1e704a0, 0x0, 0x0, 0x1e43880, 0x1e704a0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1e433c0, 0x0, 0x1e43620, 0x1e43ae0)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra.(*Command).Execute(0x1e433c0, 0xc4206d5f78, 0xc4200a4058)
	/go/src/github.com/Qihoo360/wayne/src/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/Qihoo360/wayne/src/backend/main.go:12 +0x53

**Comment by wengangJi** [comment]
Please set up MySQL image  or local MySQL and modify src/backend/conf/app.conf according to actual database configuration.To ensure the stable connection to MySQL.

**Comment by zhanghuidinah** [comment]
- Encountered the same problem.Can add a comments?

![image](https://user-images.githubusercontent.com/31201589/48702400-cd7bed80-ec2b-11e8-961f-c927ac2373a1.png)

**Comment by wengangJi** [comment]
The same problem.

**Comment by wengangJi** [comment]
Ok,thank you.
