### ISSUE TITLE
一级菜单栏会被白色样式覆盖

### ISSUE THREAD

**Issue by haoprogrammer** [Qihoo360/wayne#303]
**Describe the bug**
一级菜单栏会被白色样式覆盖

**To Reproduce**
1. 进入后台管理页
2.先 点击一级菜单 “系统统计”，在点击二级菜单“项目报表”，再点击一级菜单“系统统计”
3. 发现系统统计为被白色样式覆盖

**Expected behavior**
能展示正常一级菜单

**Screenshots**
![image](https://user-images.githubusercontent.com/31644888/53215968-f332eb80-368d-11e9-98a0-4d274330715d.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser ：chrome 72.0.3626.109 (正式版本) （64 位) 

**Server Version**
```
- Dashboard version:
- Kubernetes version:v1.13.1
- Wayne version:360cloud/wayne:v1.4.1
```

**Additional context**
目前发现 “系统统计”，“配置”，“权限”这三个一级菜单有此问题。

**Comment by wilhelmguo** [comment]
#305

**Comment by wilhelmguo** [comment]
Fixd
