### ISSUE TITLE
项目中的资源对象

### ISSUE THREAD

**Issue by wangycc** [Qihoo360/wayne#316]
### **Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/12569878/53474447-11db1d00-3aa8-11e9-9522-8d0a38255af5.png)
单个项目中可能存在多个部署集、有状态集，多个计划任务等等。如图所示，当创建多个部署时，不便于检索和管理。不清楚这样设计的目的是什么呢？

### **Describe the solution you'd like**
每个资源对象做成列表的形式？

**Comment by wilhelmguo** [comment]
@wangycc 设计为tab形式是为了方便切换和纵观全局，但是项目比较多的时候确实切换比较麻烦，有比较好的建议么？
 @BennieMeng 有时间调研下什么样的交互比较好

**Comment by wangycc** [comment]
@wilhelmguo 做成列表会不会好点，类似项目列表

**Comment by wangycc** [comment]
@wilhelmguo 还有个问题不知是不是我使用有问题，如果是多环境(机房)部署的话，在一个部署集合里面同时管理多个环境(机房)，环境多了以后可能会有误操作发生。开发人员对于多环境发布以及多环境的权限控制，有好的建议吗？

**Comment by wilhelmguo** [comment]
@wangycc 没办法做成列表，比如部署，部署和部署模版是两个不同的概念，父子关系。需要选择部署才能看到部署模版列表
