### ISSUE TITLE
您好，我每点一下界面都会报错为什么呢？帮忙解答下

### ISSUE THREAD

**Issue by kongxiaocong** [Qihoo360/wayne#32]
2018/11/20 19:26:43.275 [E] [api.go:200] System error. <nil>
2018/11/20 19:26:43.350 [E] [api.go:200] System error. <nil>
2018/11/20 19:27:29.651 [E] [api.go:200] System error. <nil>
2018/11/20 19:27:34.927 [E] [api.go:200] System error. <nil>
2018/11/20 19:27:35.884 [E] [api.go:200] System error. <nil>
2018/11/20 19:27:38.156 [E] [api.go:200] System error. <nil>
2018/11/20 19:27:45.355 [E] [api.go:200] System error. <nil>
2018/11/20 19:28:01.997 [E] [api.go:200] System error. <nil>
2018/11/20 19:28:27.279 [E] [api.go:200] System error. <nil>

**Comment by wilhelmguo** [comment]
Please provide more information about this error.
