### ISSUE TITLE
项目中，创建资源对象

### ISSUE THREAD

**Issue by wangycc** [Qihoo360/wayne#356]
**Is your feature request related to a problem? Please describe.**
建议在项目中创建资源对象(deployment、statefulset、cronjob等等)，用户可以自定义资源对象名称，而不是要求"项目名-"开头这种强制约束。以下原因:

- 在迁移过程中并没有这种强制规定去修改资源对象名称。
- 有些服务(比如微服务)不需要有项目名开头

**已经迁移的服务**
![image](https://user-images.githubusercontent.com/12569878/54405359-4c33f380-4711-11e9-93da-6ac19acd5ec8.png)

**新添加的微服务模块**
![image](https://user-images.githubusercontent.com/12569878/54405423-771e4780-4711-11e9-87c1-9f9fd5bef00b.png)

**Describe the solution you'd like**
建议这种可以通过placeholder在输入框提示更好一点，不用强制约束。

**Comment by wilhelmguo** [comment]
@wangycc  参考文档 https://360yun.org/wayne/dev/configuration.html 
配置 system.api-name-generate-rule
