### ISSUE TITLE
Support ZModem for web console 

### ISSUE THREAD

**Issue by Martinho0330** [Qihoo360/wayne#389]
**Is your feature request related to a problem? Please describe.**
There are massive request for supporting file upload/download for web console via browser, is there a way to support ZModem on xterm.js with sock remote command?

**Describe the solution you'd like**
Supporting file upload/download via browser with the web console

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/xtermjs/xterm.js/issues/279 
hearing about some interesting conversation related to this feature

**Comment by Martinho0330** [comment]
![image](https://user-images.githubusercontent.com/3690951/60663180-16b64000-9e91-11e9-9803-bd508bc0ef64.png)
I've implemented an awkward upload and download function via clicking specific button, but that's not fancy enough, since I'm not that kind of Javascript expert, I still could not manage to upload via a fancy cli-like rz -e/ sz sort of things...

**Comment by 70data** [comment]
Don't think about this design
