### ISSUE TITLE
使用wayne进行deployment扩缩容时，会自动重启原来的Pod

### ISSUE THREAD

**Issue by zhangleimxnavi** [Qihoo360/wayne#399]
使用wayne 进行 deployment 扩缩容时，会自动重启原来的Pod；
具体表现如下：
1、正常运行下的Pod
![1](https://user-images.githubusercontent.com/39846099/56342704-543cf280-61eb-11e9-9c2d-aca506317133.JPEG)
2、扩容进行中，发现原来的Pod变成了Terminating状态并启动了两个新的Pod：
![2](https://user-images.githubusercontent.com/39846099/56342711-57d07980-61eb-11e9-8573-fe70d9baa17b.JPEG)

**Comment by rockpanda** [comment]
请问下你解决了没呢，我目前也是这个问题，不知道是使用问题还是产品问题

**Comment by rockpanda** [comment]
好吧 其实就是副本限制跟回滚百分比的问题
