### ISSUE TITLE
创建namespace，按钮无法点击

### ISSUE THREAD

**Issue by wangycc** [Qihoo360/wayne#4]
![image](https://user-images.githubusercontent.com/12569878/48693316-0f009e80-ec14-11e8-9b4d-7fef3eafb780.png)
通过后台管理创建namespace时，如图所示按钮灰色 JS代码出错。

**Comment by kongxiaocong** [comment]
你居然搭建成功了 可以加个微信吗

**Comment by wilhelmguo** [comment]
refer to https://github.com/Qihoo360/wayne/pull/6

**Comment by wilhelmguo** [comment]
@wangycc  Fixed. Please pull latest docker image.

**Comment by Cloudzp** [comment]
![image](https://user-images.githubusercontent.com/25190767/48715521-29586d80-ec50-11e8-9034-500d5810255d.png)

**Comment by hihunk** [comment]
> @wangycc Fixed. Please pull latest docker image.

赞，自己折腾了半天，看了一下这个issue，好吧，重拉了镜像好了
