### ISSUE TITLE
创建命名空间

### ISSUE THREAD

**Issue by HarveyJie** [Qihoo360/wayne#40]
**Describe the bug**
界面创建成功了，但是k8s后台查不到创建的命名空间

**Comment by motecshine** [comment]
你应该 看下文档 wayne 的ns 不是 k8s的 ns， 是 一个他们自己虚构出来的概念 类似有group

**Comment by wilhelmguo** [comment]
refer to https://github.com/Qihoo360/wayne/wiki/Wayne-admin-namespace
