### ISSUE TITLE
click Kubernetes -> Service, error occur.

### ISSUE THREAD

**Issue by kaybinwong** [Qihoo360/wayne#407]
**Describe the bug**
click Kubernetes -> Service, error occur.

**To Reproduce**
进入后台，点击Kubernetes，点击Service报错，导致所有页面无法继续操作。

**Comment by 70data** [comment]
请问有具体信息或是页面截图么？

**Comment by wannady** [comment]
1.点service，不显示列表，后端接口看着都返回了
<img width="1689" alt="企业微信截图_7999e577-63ed-48d1-8485-2c14477964d4" src="https://user-images.githubusercontent.com/36806194/132319536-67a968e5-d1ef-4682-8aba-39c5dff6906c.png">
2.再点其它页面，都出现error，除非刷新下才行
<img width="865" alt="企业微信截图_b143b12f-5864-4cad-9466-43c91a78361d" src="https://user-images.githubusercontent.com/36806194/132319660-6f9a6803-eb74-401a-bcc6-d8773a895ce7.png">

**Comment by wannady** [comment]
> **Describe the bug**
> click Kubernetes -> Service, error occur.
> 
> **To Reproduce**
> 进入后台，点击Kubernetes，点击Service报错，导致所有页面无法继续操作。

请问后续怎么解决的呢
