### ISSUE TITLE
为命名空间或项目配置用户出错

### ISSUE THREAD

**Issue by guobayang** [Qihoo360/wayne#41]
设置提交后，UI弹出以下错误。

Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'wayne.T0.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by chengyumeng** [comment]
Please Read FAQ:https://github.com/Qihoo360/wayne/wiki/FAQ#MySQL
