### ISSUE TITLE
增加cluster时无法识别  insecure-skip-tls-verify: true

### ISSUE THREAD

**Issue by kineta-Jiang** [Qihoo360/wayne#410]
**Describe the bug**
增加一个cluster时，配置中加入insecure-skip-tls-verify: true,系统报错

**To Reproduce**
1. 管理员登陆后台
2.集群－列表－关联集群－kube-config
3. 配置

- cluster:
    insecure-skip-tls-verify: true
    server: https://xxx.xxx.xx.xx.:6443

**Expected behavior**
[client.go:192] json unmarshal kubeconfig error. json: cannot unmarshal string into Go struct field Cluster.insecure-skip-tls-verify of type bool

**Server Version**
```
- Dashboard version:
- Kubernetes version: 1.11.5
- Wayne version: v1.6.1
- Node.js version:
- Go version:
```
wayne在集群配置中不能识别 insecure-skip-tls-verify: true

**Comment by daigong** [comment]
Hello，我这边是可以的，配置



apiVersion: v1
clusters:
  \- cluster:
      insecure-skip-tls-verify: true
