### ISSUE TITLE
PVC详情的扩展看板功能无效，js错误 Uncaught TypeError: Cannot read property 'nativeElement' of undefined

### ISSUE THREAD

**Issue by zhanghuidinah** [Qihoo360/wayne#43]
**Describe the bug**
- PVC详情的扩展看板功能无效，js错误 Uncaught TypeError: Cannot read property 'nativeElement' of undefined

**To Reproduce**
1. Go to 'PVC详情'
2. Click on '扩展看板'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31201589/48829477-3ccd1b00-edad-11e8-9566-a8579ca80eba.png)

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by wilhelmguo** [comment]
FIXED
