### ISSUE TITLE
wayne使用ingress后，进入容器失败

### ISSUE THREAD

**Issue by newyue588cc** [Qihoo360/wayne#431]
**说明**
wayne version: v1.6.4

**现象**
1. 使用nodeport方式访问wayne，从dashboard进入容器功能正常
2. 使用clusterip替代nodeport后，前端使用ingress后，从dashboard进入容器功能失败。

**日志**
从后台日志查看，抛出以下错误：
2019/06/19 13:16:48.223 [E] [logged.go:120] Exception (504) Reason: "channel/connection is not open"
2019/06/19 13:17:09.393 [E] [terminal.go:114] handleTerminalSession: can't Recv: sockjs: session not in open state
2019/06/19 13:17:12.349 [E] [logged.go:120] Exception (504) Reason: "channel/connection is not open"

从日志跑错去源代码查看后，也无法确认到底是哪里的问题导致进入pod功能失败。

**Comment by gaulzhw** [comment]
see #432

**Comment by newyue588cc** [comment]
> see #432

Thanks
