### ISSUE TITLE
wayne升级到1.7.0版本后，进入容器失败。显示：connection closed

### ISSUE THREAD

**Issue by yjwlyy** [Qihoo360/wayne#432]
版本
wayne version: v1.7.0
部署
按照默认的yaml文件在k8s里创建服务，使用nodeport方式进行访问（wayne.backend添加到本机的hosts文件）
遇到问题
进入容器时，显示connection closed
从浏览器上看有如下报错：
![image](https://user-images.githubusercontent.com/23089714/59742771-04d57a00-92a1-11e9-8a8a-4da5b0ab1ada.png)

**Comment by luolizhi** [comment]
同样的问题。

**Comment by yyssff90** [comment]
同样的问题。初步认为是前后分离导致的吧

**Comment by 70data** [comment]
目前看确实有这个问题
但我们这还做不到稳定复现，只是偶发，不太好定位问题。

能否提供详细的部署数据
前端/后端部署方式：docker compose/k8s
是否使用ingress：是/否
部署实例：？
是否能稳定复现或是否有复现步骤？

**Comment by yjwlyy** [comment]
> 目前看确实有这个问题
> 但我们这还做不到稳定复现，只是偶发，不太好定位问题。
> 
> 能否提供详细的部署数据，并贴一下你的相关配置文件
> 
> 前端/后端部署方式：docker compose/k8s
> 部署实例：？
> 访问方式：nodeport/ingress
> 
> 是否能稳定复现或是否有复现步骤？

部署是直接执行wayne-1.7.0/hack/kubernetes下的yaml文件，一点没做更改
访问也就是按照yaml里写的nodeport的方式，只是需要把wayne.backend在本机hosts里做下映射
问题是100%重新的（pod是通过后台迁移过去的，然后在前台进入容器的时候就会出现此问题）

**Comment by gaulzhw** [comment]
这是所有进入容器的操作都会出现，还是部分才有问题？

**Comment by 70data** [comment]
@yjwlyy 
已经更新了 1.7.1 修复了这个问题
请升级试试

**Comment by gaulzhw** [comment]
update in v1.7.1, close
