### ISSUE TITLE
show time in pod log

### ISSUE THREAD

**Issue by liqiangno1** [Qihoo360/wayne#434]
**Describe the solution you'd like**
查看日志无法看到日志发生时间，希望加上

**Comment by gaulzhw** [comment]
日志是自己加的信息，业务日志中加上时间就可以了啊

**Comment by liqiangno1** [comment]
> 日志是自己加的信息，业务日志中加上时间就可以了啊

有些系统没有按规范来，特别是一些第三方得系统，所以希望按照K8S dashboard那样，给个选项，是否显示日志时间
