### ISSUE TITLE
docker-compose 安装后 web 连接一片空白

### ISSUE THREAD

**Issue by kong62** [Qihoo360/wayne#437]
docker-compose 安装后 web 连接一片空白

版本： 1.7.0 和 1.7.1 都是这样的问题

wayne-frontend_1 日志：
wayne-frontend_1  | 172.16.50.177 - - [24/Jun/2019:15:47:15 +0800] "GET / HTTP/1.1" 200 859 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
wayne-frontend_1  | 172.16.50.177 - - [24/Jun/2019:15:47:15 +0800] "GET /config.js?v=1 HTTP/1.1" 200 100 "http://10.64.57.71:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
wayne-frontend_1  | 172.16.50.177 - - [24/Jun/2019:15:47:15 +0800] "GET /runtime.b57bf819d5bdce77f1c7.js HTTP/1.1" 200 1440 "http://10.64.57.71:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
wayne-frontend_1  | 172.16.50.177 - - [24/Jun/2019:15:47:15 +0800] "GET /polyfills.a82026cfedee8b869738.js HTTP/1.1" 200 55313 "http://10.64.57.71:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
wayne-frontend_1  | 172.16.50.177 - - [24/Jun/2019:15:47:15 +0800] "GET /styles.705f39d604a5c3b65a82.css HTTP/1.1" 200 439883 "http://10.64.57.71:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
wayne-frontend_1  | 172.16.50.177 - - [24/Jun/2019:15:47:15 +0800] "GET /scripts.ded66b0a02e53aefc061.js HTTP/1.1" 200 677941 "http://10.64.57.71:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
wayne-frontend_1  | 172.16.50.177 - - [24/Jun/2019:15:47:16 +0800] "GET /vendor.42cbfda7a5931e52630c.js HTTP/1.1" 200 3986731 "http://10.64.57.71:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
wayne-frontend_1  | 172.16.50.177 - - [24/Jun/2019:15:47:16 +0800] "GET /main.b968205b56d4368d250d.js HTTP/1.1" 200 4212060 "http://10.64.57.71:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
wayne-frontend_1  | 172.16.50.177 - - [24/Jun/2019:15:47:19 +0800] "GET /assets/i18n/zh-Hans.json?v=1.7.0 HTTP/1.1" 200 27437 "http://10.64.57.71:4200/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"

wayne-backend 日志：
wayne-backend_1   | 2019/06/24 15:46:56.236 [I] [asm_amd64.s:1337]  http server Running on http://:8080
wayne-backend_1   | 2019/06/24 15:46:56.236 [I] [asm_amd64.s:1337]  Admin server Running on :8088

**Comment by gaulzhw** [comment]
怎么部署，怎么访问，能提供截图吗

**Comment by kong62** [comment]
@gaulzhw 

安装部署：
wget -c -O wayne_v1.7.1.tar.gz https://github.com/Qihoo360/wayne/archive/v1.7.1.tar.gz
tar -zxvf wayne_*.tar.gz
cd wayne-*
cd hack/docker-compose/
docker-compose up -d mysql
docker-compose up -d rabbitmq
docker-compose up -d wayne-backend
docker-compose up -d wayne-frontend
 docker-compose ps
         Name                   Command          State           Ports        
------------------------------------------------------------------------------
dockercompose_mysql_1    docker-entrypoint.sh    Up      0.0.0.0:3306->3306/tc
                         mysqld                          p                    
dockercompose_rabbitmq   docker-entrypoint.sh    Up      15671/tcp, 15672/tcp,
_1                       rabbi ...                       25672/tcp, 4369/tcp, 
                                                         5671/tcp, 0.0.0.0:567
                                                         2->5672/tcp          
dockercompose_wayne-     /opt/wayne/backend      Up      0.0.0.0:8080->8080/tc
backend_1                apiserver                       p                    
dockercompose_wayne-     /usr/local/openresty/   Up      0.0.0.0:4200->80/tcp 
frontend_1               bin/o ...                   

访问浏览器：
![傲游截图20190625101226](https://user-images.githubusercontent.com/10241723/60064085-da1c7300-9731-11e9-806e-c6e4eff0687e.png)

查看日志：
![傲游截图20190625101259](https://user-images.githubusercontent.com/10241723/60064089-df79bd80-9731-11e9-8391-9463e2bba942.png)

**Comment by gaulzhw** [comment]
请修改 conf/config.js 下的配置文件
URL 填写后端服务器 ip 地址

**Comment by kerven88** [comment]
> 请修改 conf/config.js 下的配置文件
> URL 填写后端服务器 ip 地址

我用docker-compose起的，首页也是空白。
请问这个config.js里面的配置是啥意思，需要修改成哪个ip？
window.CONFIG = {
    URL: 'http://localhost:8080',
    RAVEN: false,
    RAVEN_DSN: 'RAVEN_DSN'
};

**Comment by kerven88** [comment]
> @gaulzhw
> 
> 安装
> 
> wget -c -O wayne_v1.7.1.tar.gz https://github.com/Qihoo360/wayne/archive/v1.7.1.tar.gz
> tar -zxvf wayne__.tar.gz cd wayne-_
> cd hack/docker-compose/
> docker-compose up -d mysql
> docker-compose up -d rabbitmq
> docker-compose up -d wayne-backend
> docker-compose up -d wayne-frontend
> docker-compose ps
> Name Command State Ports
> dockercompose_mysql_1 docker-entrypoint.sh Up 0.0.0.0:3306->3306/tc
> mysqld p
> dockercompose_rabbitmq docker-entrypoint.sh Up 15671/tcp, 15672/tcp,
> _1 rabbi ... 25672/tcp, 4369/tcp,
> 5671/tcp, 0.0.0.0:567
> 2->5672/tcp
> dockercompose_wayne- /opt/wayne/backend Up 0.0.0.0:8080->8080/tc
> backend_1 apiserver p
> dockercompose_wayne- /usr/local/openresty/ Up 0.0.0.0:4200->80/tcp
> frontend_1 bin/o ...
> 
> 访问浏览器
> 回车后看到界面有圈在转
> ![1](https://user-images.githubusercontent.com/10241723/60064143-12bc4c80-9732-11e9-959f-56ef25b169da.png)
> 几秒后就变成一片空白了，没登录窗口
> ![傲游截图20190625101226](https://user-images.githubusercontent.com/10241723/60064085-da1c7300-9731-11e9-806e-c6e4eff0687e.png)
> 
> 查看日志：
> ![傲游截图20190625101259](https://user-images.githubusercontent.com/10241723/60064089-df79bd80-9731-11e9-8391-9463e2bba942.png)

兄弟你的首页可以打开了吗？

**Comment by kong62** [comment]
@gaulzhw 
# vi conf/config.js 
window.CONFIG = {
    URL: 'http://172.17.0.4:8080',
    RAVEN: false,
    RAVEN_DSN: 'RAVEN_DSN'
};

我这里写了后端容器的IP，还是一样空白， 前后端的日志已经如上图 - -！

**Comment by 70data** [comment]
http://172.17.0.4:8080
请确保填写本地浏览器可以访问的后端地址
