### ISSUE TITLE
发布部署报错

### ISSUE THREAD

**Issue by longpan** [Qihoo360/wayne#438]
![image](https://user-images.githubusercontent.com/5399632/60165606-2949cd00-9832-11e9-8aa9-8792d265f3e3.png)
发布部署时报错： 0/1 nodes are available: 1 Insufficient cpu.
这是我的k8s node情况：
![image](https://user-images.githubusercontent.com/5399632/60165700-54ccb780-9832-11e9-9441-f6d0b57ba7f7.png)

k8s是用Kubadm搭建的单机node,  机器配置为2G1核，

Wayne 是使用命令启动：
docker run -d  -e GOPATH=/go -v /root/wayne/tmp/dev.conf:/opt/wayne/conf/dev.conf -p 8080:8080 360cloud/wayne /opt/wayne/backend apiserver

这个问题是不是k8s node 的内存和cpu不够造成的呢？

**Server Version**
```
- Dashboard version:
- Kubernetes version: v1.14.3
- Wayne version:  360cloud/wayne:latest
- Node.js version:
- Go version:
```

**Comment by gaulzhw** [comment]
资源不足，检查node的可用资源数，以及部署的时候申请的资源数

**Comment by longpan** [comment]
多谢回答
