### ISSUE TITLE
config.js URL使用服务名称前端会空白，使用nodeport方式可以正常显示

### ISSUE THREAD

**Issue by newyue588cc** [Qihoo360/wayne#439]
故障说明：
-    从1.6.2升级到1.7.0,升级过程中，发现wayne-frontend.yaml中的config.js中的URL使用service名称和ingress域名方式后，前端均出现白屏。测试直接使用nodeport方式后正常。
-   v1.7.1的镜像界面上还是显示wayne1.7.0,未修改成1.7.1

故障现象截图：
![wayne1](https://user-images.githubusercontent.com/3349048/60241288-818dd700-98e5-11e9-9e3a-e9b0c16acf3d.png)
![wayne2](https://user-images.githubusercontent.com/3349048/60241299-8e122f80-98e5-11e9-94f1-2feec4993b22.png)

文件修改信息如下：
wayne-frontend.yaml 中的configmap部分：
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: wayne-frontend-test
  name: wayne-frontend-test
  namespace: wayne
data:
  config.js: |-
    window.CONFIG = {
      URL: 'http://此处使用ingress或者service名称:8080均白屏，只有nodeport方式加端口正常',
      RAVEN: false,
      RAVEN_DSN: 'RAVEN_DSN'
    };

**Comment by gaulzhw** [comment]
URL: 'http://此处使用ingress或者service名称:8080均白屏，只有nodeport方式加端口正常',

请确保填写本地浏览器可以访问的后端地址

**Comment by newyue588cc** [comment]
@gaulzhw 谢谢，可能是我前面升级不严谨导致。另外，调用openapi是不是不能用frontend的ingress域名，只能使用后端域名来调用吗？
