### ISSUE TITLE
创建部署的时候，会有费用显示

### ISSUE THREAD

**Issue by shuoshadow** [Qihoo360/wayne#443]
![image](https://user-images.githubusercontent.com/10016360/60582835-23b52f80-9dbc-11e9-86d8-d7c913ece79d.png)

内部使用的话是不需要这个的，建议去掉。或者可以自己配置可显示/不显示

**Comment by 70data** [comment]
后续会变成可选项

**Comment by 70data** [comment]
has mark it at https://github.com/Qihoo360/wayne/issues/394
