### ISSUE TITLE
前端代码使用类似@的路径import

### ISSUE THREAD

**Issue by abbform** [Qihoo360/wayne#446]
from
import { AppService } from '../../../shared/client/v1/app.service';
to
import { AppService } from '@/shared/client/v1/app.service';
or
import { AppService } from '@shared/client/v1/app.service';
像这样
https://stackoverflow.com/questions/43281741/how-to-use-paths-in-tsconfig-json

**Comment by BennieMeng** [comment]
wo can also use app/shared to realize, if you have interest to do this, we would be appreciate it.
