### ISSUE TITLE
前台页面空白

### ISSUE THREAD

**Issue by yanruogu** [Qihoo360/wayne#449]
**Describe the bug**

安装成功后，可以打开登录页，使用admin正常登录后，再退出，再次登录，变成空白页

调试发现js抛出如下异常：

![image](https://user-images.githubusercontent.com/5188514/61441509-5fcdc000-a978-11e9-9d5e-548e5dc36dab.png)

js文件： http://xxx/polyfills.a82026cfedee8b869738.js

wayne版本：v1.7.1

安装方式：
/wayne-1.7.1/hack/kubernetes# ls
mysql.yaml  rabbitmq.yaml  wayne-backend.yaml  wayne-frontend.yaml

直接通过kubernetes安装，kubernetes版本是1.10.7

**Comment by jansure** [comment]
遇到同样的问题

**Comment by jansure** [comment]
![image](https://user-images.githubusercontent.com/25276270/61581115-a3792300-ab4c-11e9-8ce9-c0754cfc7457.png)
更改了backend的pod地址也不管用

**Comment by wanghaiqing2015** [comment]
你们访问的什么地址，我的连前端界面都打不开，console就报错了。

**Comment by tongxin1994** [comment]
要把wayne-frontend.yaml里面configMap的wayne.backend改成某一个node的ip就可以了

**Comment by 70data** [comment]
这是由于前后端配置有问题导致的
近期我们会发布一个简易版安装程序
