### ISSUE TITLE
1.7.1的目录结构有很大的调整，原安装文档需要相应调整。

### ISSUE THREAD

**Issue by gotoworld** [Qihoo360/wayne#453]
**  1.7.1的目录结构有很大的调整，原安装文档需要相应调整。**

附：1.7.1 的hack目录结构
![image](https://user-images.githubusercontent.com/8605471/62764320-2c3a0d80-bac0-11e9-8f53-86e1e894fce4.png)
![image](https://user-images.githubusercontent.com/8605471/62764348-3f4cdd80-bac0-11e9-8e67-0b85ec9e420f.png)

附：1.6的目录结构
![image](https://user-images.githubusercontent.com/8605471/62764363-4bd13600-bac0-11e9-9349-86abafbb65b2.png)

**安装指导文档**

附：错误的，不及时的文档
![image](https://user-images.githubusercontent.com/8605471/62764441-7ae7a780-bac0-11e9-929b-7b4b852c8a99.png)

![image](https://user-images.githubusercontent.com/8605471/62764511-a79bbf00-bac0-11e9-8d01-f5a261a1a589.png)

**Comment by troycheng** [comment]
请求及时更新相关文档

**Comment by 70data** [comment]
新的文档正在写了。
完成后统一更新。
