### ISSUE TITLE
Should be image: '360cloud/wayne-backend:V1.6.0' , but not latest instend,  since i use tags of V1.6.1

### ISSUE THREAD

**Issue by gotoworld** [Qihoo360/wayne#454]
**Describe the bug**
Should be image: '360cloud/wayne-backend:V1.6.0' , but not latest instend,  since i use tags of V1.6.1

**To Reproduce**
![image](https://user-images.githubusercontent.com/8605471/62776704-f3a92c80-badd-11e9-98a8-df072eff77e6.png)

with the old version use the "lastest" as version,  then i never can get the corresponding version。

**Comment by 70data** [comment]
This is a bug.
I will adjust it most recently.
