### ISSUE TITLE
如何实现扩缩容，而不是重新创建所有pod

### ISSUE THREAD

**Issue by ndaysy** [Qihoo360/wayne#458]
发布一个运行中的deployment时调整副本数，总是会结束原有pod重新创建，看起来执行的是滚动更新操作吧？
应该如何操作才能保留原有pod，实现kubectl scale的扩缩容效果

**Comment by 70data** [comment]
只调整副本数这个功能正在做了。
完成后会随版本上线。

**Comment by 70data** [comment]
The feature has done.
Commit by this. https://github.com/Qihoo360/wayne/issues
