### ISSUE TITLE
js阻塞？

### ISSUE THREAD

**Issue by tongxin1994** [Qihoo360/wayne#465]
在登陆界面或者前台跳转到后台时加载很慢。前台版本是1.8.0 
![image](https://user-images.githubusercontent.com/14275468/64690120-3d60aa80-d4c2-11e9-9f2c-b81d46f8d9d2.png)

**Comment by ody123** [comment]
我也一样，每次在请求后端的currentuser之前都要loading 20~30s
![QQ图片20190911225012](https://user-images.githubusercontent.com/36733129/64708577-69daed80-d4e7-11e9-8c83-70a0d4a36b8f.png)

**Comment by J2AZYZ** [comment]
我也是同样的问题

**Comment by J2AZYZ** [comment]
谁能帮忙看看这个问题吗？

**Comment by MirrorTown** [comment]
一样的问题，求前段大佬help

**Comment by luolizhi** [comment]
一样的问题， 1.8.0 版本生存的vendor.js 太大了，有 5M 多。

**Comment by GallenHu** [comment]
编译时添加`--aot`选项可以减少浏览器中的加载时间，但是这会使终端里的编译时间会增加

**Comment by BennieMeng** [comment]
推荐使用 npm run build:aot
