### ISSUE TITLE
wayne-backend编译报错，显示缺少参数

### ISSUE THREAD

**Issue by hanlimo** [Qihoo360/wayne#466]
在后端编译时卡在这里，这是什么原因导致的？
2019/09/12 15:27:20 ERROR    ▶ 0003 Failed to build the application: # k8s.io/client-go/rest
/Users/hanlimo/go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/rest/request.go:598:31: not enough arguments in call to watch.NewStreamWatcher
	have (*versioned.Decoder)
	want (watch.Decoder, watch.Reporter)

**Comment by 70data** [comment]
如何编译的？
Go版本 操作系统 操作步骤能否提供一下？

**Comment by 70data** [comment]
这个应该是使用的client-go版本不一致导致的
目前仓库里的go.mod是可以正常编译运行的
