### ISSUE TITLE
想问下几个问题？跪求大佬解答

### ISSUE THREAD

**Issue by AlexKingGo** [Qihoo360/wayne#467]
本人菜鸡，最近在研究学习贵公司的wayne，遇到了几个问题，想问下大佬。
1.API key在什么业务场景下用到？具体作用是啥
2.数据库中有些表的后缀带template是什么意思？这个表的作用是什么
3.webhook具体作用

**Comment by AlexKingGo** [comment]
还有就是很多表中 有一个字段  叫  order_id，这个字段是什么意思呢？求大佬解答！

**Comment by 70data** [comment]
请阅读相关文档
https://360yun.org/wayne/portal/openapi.html
