### ISSUE TITLE
初次打开前端页面或者刷新页面很慢，大约16s左右

### ISSUE THREAD

**Issue by J2AZYZ** [Qihoo360/wayne#468]
初次打开前端页面或者刷新页面很慢，大约16s左右

**Comment by yumingguo** [comment]
我根本都打不开

**Comment by J2AZYZ** [comment]
> 我根本都打不开
打不开是不是有些config没有改啊？

**Comment by J2AZYZ** [comment]
@yumingguo 打不开是不是配置没有改啊？

**Comment by NaixHake** [comment]
我试了很多次，都是页面都刷新不出来，是需要配置？ @J2AZYZ

**Comment by J2AZYZ** [comment]
@NaixHake 是的，configmap里面的配置需要更改成你自己的相关配置

**Comment by NaixHake** [comment]
好的，谢谢提醒，我试试 @J2AZYZ

**Comment by J2AZYZ** [comment]
我先回退到1.6.1版本了

**Comment by NaixHake** [comment]
我试了一下修改configmap里面的配置，因为他这个前后端分开的，都需要改吗，在kubernetes这里面有对应的yaml文件，我也把wayne-frontend.yaml里面configMap的wayne.backend改成某一个node的ip，记过还是空白加载不出来 @ @J2AZYZ 
![image](https://user-images.githubusercontent.com/55433169/65510173-e073e400-df06-11e9-8ac2-e2b17e107b31.png)

**Comment by J2AZYZ** [comment]
@NaixHake 你应该没改吧，请求里面还是请求的localhost啊，把那个配置改成你集群的一个nodeip就可以了

**Comment by NaixHake** [comment]
嗯嗯，可以了，我改错地方了，谢啦 @J2AZYZ

**Comment by 70data** [comment]
前后端配置的问题 近期会更新一个简易版部署方式
