### ISSUE TITLE
前面网页提示Not Found

### ISSUE THREAD

**Issue by evenye** [Qihoo360/wayne#469]
1. git clone https://github.com/Qihoo360/wayne.git
2. 安装docker client
3. 运行docker-compose -f ./hack/docker-compose/docker-compose.yaml up
并没有出现任何错误:
rabbitmq_1        | 2019-09-24 03:15:40.125 [info] <0.646.0> accepting AMQP connection <0.646.0> (172.18.0.4:58586 -> 172.18.0.2:5672)
rabbitmq_1        | 2019-09-24 03:15:40.183 [info] <0.646.0> connection <0.646.0> (172.18.0.4:58586 -> 172.18.0.2:5672): user 'guest' authenticated and granted access to vhost '/'
wayne-backend_1   | 2019/09/24 11:15:40.253 [I] [asm_amd64.s:1337]  http server Running on http://:8080
wayne-backend_1   | 2019/09/24 11:15:40.253 [I] [asm_amd64.s:1337]  Admin server Running on :8088
wayne-backend_1   | 2019/09/24 11:15:40.253 [I] [asm_amd64.s:1337]  http server Running on http://:8080
wayne-backend_1   | 2019/09/24 11:15:40.253 [I] [asm_amd64.s:1337]  Admin server Running on :8088

然后打开网页http://host:8080 ,提示
Not Found

The page you have requested has flown the coop.
Perhaps you are here because:

The page has moved
The page no longer exists
You were looking for your puppy and got lost
You like 404 pages

请问这是什么原因呢? 需要修改什么配置内容吗?

**Comment by evenye** [comment]
如果直接打开http://host:80,这里只显示welcome to nginx...

**Comment by evenye** [comment]
如果直接打开http://host:4200 则显示空白的loading ...

**Comment by 70data** [comment]
前后端配置的问题 近期会更新一个简易版部署方式
