### ISSUE TITLE
安装wayne，4200端口页面空白？

### ISSUE THREAD

**Issue by ckgmg** [Qihoo360/wayne#471]
安装docker-compose -f ./hack/docker-compose/docker-compose.yaml up

![image](https://user-images.githubusercontent.com/49260651/65580113-a1e43500-dfab-11e9-89e2-66a0831310d2.png)
到这里已经安装成功！

![image](https://user-images.githubusercontent.com/49260651/65580184-c50ee480-dfab-11e9-93e4-efe565037c33.png)

![image](https://user-images.githubusercontent.com/49260651/65580216-d0621000-dfab-11e9-8a1e-330fbf7a9fb8.png)
一直空白

请问是什么问题？

**Comment by ckgmg** [comment]
等了1分钟才出现界面
![image](https://user-images.githubusercontent.com/49260651/65580603-90e7f380-dfac-11e9-9ee4-f8fd89f64093.png)
界面不给登录，还有没显示字体，使用google浏览器，

**Comment by 70data** [comment]
是否是由于没有初始化集群造成的？

**Comment by liulangwa** [comment]
@ckgmg 需要修改conf/config.js中后端的地址 URL: 'http://xxx.xxx.xxx.xxx:8080',这个地址必须是浏览器可访问的
