### ISSUE TITLE
`dev.conf `挂在 `/tmp`下不是很友好，电脑重启需重新install

### ISSUE THREAD

**Issue by zhanghuidinah** [Qihoo360/wayne#48]
**Describe the bug**

**To Reproduce**
1. Go to '电脑restart'
2. Click on 'docker run wanye'
3. See error
```
panic: read /opt/wayne/conf/dev.conf: is a directory

goroutine 1 [running]:
xxxxxxxxx
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by wilhelmguo** [comment]
挂载 /tmp下只是Quick start让使用者快速启动预览效果，真正使用建议使用Kubernetes部署的方式
