### ISSUE TITLE
启动后一直报这个错误，web页面访问不了

### ISSUE THREAD

**Issue by shinynz** [Qihoo360/wayne#49]
2018/11/22 15:46:00.955 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:46:06.000 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:46:11.047 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:46:16.080 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:46:21.113 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:46:26.146 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:46:31.307 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:46:36.356 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:46:41.389 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:46:46.431 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:46:51.474 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:46:56.510 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:47:01.671 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:47:06.705 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:47:11.749 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:47:16.786 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:47:21.827 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:47:26.869 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:47:32.033 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:47:37.067 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:47:42.110 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist
2018/11/22 15:47:47.150 [E] [client.go:59] build apiserver client get all cluster error. Error 1146: Table 'wayne.cluster' doesn't exist

**Comment by cx2c** [comment]
hi 这个问题是怎么解决的呢，我的数据库也没有初始数据

**Comment by khs1994** [comment]
不要事先创建使用的数据库
