### ISSUE TITLE
Docker-Compose部署后，4200端口访问白屏。

### ISSUE THREAD

**Issue by ysx1535** [Qihoo360/wayne#493]
Docker-Compose部署后，日志出现如下提示：
wayne-backend_1   | panic: dial tcp 10.142.103.38:2169: connect: connection timed out
这IP并未配置到配置文件中，请问该如何处理？
日志截图如下：
![图片](https://user-images.githubusercontent.com/1997041/67462819-d9a9cf80-f672-11e9-99ae-81022031da06.png)

**Comment by sjc960115** [comment]
InitDb报错，看起来像是mysql配置的问题

**Comment by ysx1535** [comment]
> 
> 
> InitDb报错，看起来像是mysql配置的问题

确实是数据库配置的问题，数据库连接DBTNS配置错了。
谢谢！
