### ISSUE TITLE
前端ts中函数类型错误

### ISSUE THREAD

**Issue by JiaoZhengYa** [Qihoo360/wayne#497]
frontend/diff下diff.component.ts第99报函数的入参不匹配
![image](https://user-images.githubusercontent.com/54496812/67841847-ec6d4a00-fb33-11e9-9f4b-03a8154dd959.png) 
![image](https://user-images.githubusercontent.com/54496812/67841978-3eae6b00-fb34-11e9-9bf1-35c3386c0af0.png)

**Comment by BennieMeng** [comment]
![image](https://user-images.githubusercontent.com/37033797/69316140-22a17380-0c73-11ea-8d26-b656d89e952f.png)
请确认你下载了对应的插件版本，我这里显示的是需要的string
