### ISSUE TITLE
1.16版本API

### ISSUE THREAD

**Issue by password36** [Qihoo360/wayne#501]
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
K8S 1.16版本主要对一些存在在v1beta命名空间下的接口进行了升级，升级到apps/v1下面
1.8.0-1.8.4版本链接1.16版本APISERVER会报如下的错误：

E1031 09:14:33.607725       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1031 09:14:33.696320       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.ReplicaSet: the server could not find the requested resource
E1031 09:14:33.840585       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.Deployment: the server could not find the requested resource
E1031 09:14:33.935206       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.StatefulSet: the server could not find the requested resource
E1031 09:14:34.020665       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.DaemonSet: the server could not find the requested resource
E1031 09:14:34.370759       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1beta1.ReplicaSet: the server could not find the requested resource

或者是否有更快捷的配置升级的方式，请告知。
十分感谢。

**Comment by 70data** [comment]
目前已知的最后一个可用版本应该是1.15
1.16需要对client-go的调用以及wayne本身的设计进行升级
这是一个已知的问题 目前在做 但还没完成

**Comment by 70data** [comment]
see this.
https://github.com/Qihoo360/wayne/issues/522
