### ISSUE TITLE
list-customlink.component.ts变量类型错误，导致页面显示异常

### ISSUE THREAD

**Issue by MirrorTown** [Qihoo360/wayne#502]
**Describe the bug**
wayne/src/frontend/src/app/admin/customlink/list-customlink/list-customlink.component.ts该文件中的@Input() configs: Config[];类型错误导致customlink.component.html的handler处理函数接受参数类型不匹配错误

**To Reproduce**
1. Go to 'list-customlink.component.ts'
2. Click on 'customlink.component.html'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**
该正常变量类型是否应该为:Customlink[]

**Comment by BennieMeng** [comment]
https://github.com/Qihoo360/wayne/pull/514
