### ISSUE TITLE
Ingress 添加或编辑 annotations 后，点击发布不能立即生效

### ISSUE THREAD

**Issue by kankanreno** [Qihoo360/wayne#504]
**Describe the bug**
Ingress 添加或编辑 annotations 后，点击发布不能立即生效。

**To Reproduce**
1. 新建并发布第一个 Ingress
2. 克隆上步 Ingress 并添加或编辑其 annotations， 得到一个新的 Ingress
3. 直接发布新的 Ingress
4. 新 Ingress 的 annotations 并未生效，到终端使用 kubectl 查看新 Ingress，可以发现新 Ingress 并未成功添加或编辑其 annotations

**Expected behavior**
新 Ingress 可以直接点击发布时，其 annotations 能立即生效。

**Screenshots**

**Server Version**
```
- Kubernetes version: 1.14
- Wayne version: 1.8.0
- Go version: 1.12.6
```

**Additional context**
在 wayne 源码中找到 Ingress 的发布方法代码，可以发现发布新 Ingress 时，只使用到了新 Ingress 的 spec 相关属性，并未用到 annotations 相关属性，这是此问题产生的原因，在增加了使用  annotations 属性代码后，上述问题得到解决，只是不明白这样加了是否会导致一些其它问题，所以官方源码上没有加上此代码。

**Comment by newyue588cc** [comment]
遇到相同的问题，在dashboard中增加annotations后，通过服务器端kubectl查看，并未生成新的annotations。

**Comment by codeb2cc** [comment]
@kankanreno 历史遗留的设计问题，几年前Annotations一般不影响对象的执行逻辑所以不会触发重建，但现在这假设明显不成立了，提个PR给他们吧。

**Comment by newyue588cc** [comment]
这个bug我看在最新的commit中已经修复，大概什么时间会发版？我们目前正好要用。

**Comment by 70data** [comment]
已经修复
