### ISSUE TITLE
ldap认证fail

### ISSUE THREAD

**Issue by smallwinterfeng** [Qihoo360/wayne#505]
**Describe the bug**
2019/11/07 10:51:57.783 [W] [ldap.go:74]  Not found an entry.
2019/11/07 10:51:57.783 [W] [authenticator.go:104]  try to login in with user (xxxx) error Not found an entry. .

关于配置ldap_filter:
ldap_filter = "(&(sAMAccountName=%s))"
ldap_uid = "sAMAccountName"

不知道这样配置是否可以？

**Comment by zhangzhaorui** [comment]
大佬遇到过这个问题吗？ ldap: finished compiling filter with extra at end: bjectClass=inetOrgPerson(uid=zhangzhaorui)).  好像 wayne读取objectClass 字段少一个o

2019/11/18 22:59:04.813 [W] [ldap.go:69]  ldap search fail: LDAP Result Code 201 "Filter Compile Error": ldap: finished compiling filter with extra at end: bjectClass=inetOrgPerson(uid=zhangzhaorui))
2019/11/18 22:59:04.813 [W] [authenticator.go:104]  try to login in with user (zhangzhaorui) error LDAP Result Code 201 "Filter Compile Error": ldap: finished compiling filter with extra at end: bjectClass=inetOrgPerson(uid=zhangzhaorui)).

**Comment by smallwinterfeng** [comment]
你的ldap配置是怎样的？

**Comment by ysicing** [comment]
@smallwinterfeng  @zhangzhaorui  你们ldap配置ok了么？

**Comment by smallwinterfeng** [comment]
> @smallwinterfeng @zhangzhaorui 你们ldap配置ok了么？

@ysicing 我的配置OK了

**Comment by ysicing** [comment]
我的大概配置如下: 具体参数根据情况替换😄
```
enabled = true
ldap_url = "ldap://192.168.0.1:389"
ldap_search_dn = "cn=ldapsearch,ou=special,dc=example,dc=com"
ldap_search_password = "************"
ldap_base_dn = "ou=www,dc=example,dc=com"
ldap_uid = cn
ldap_scope = 3
ldap_connection_timeout = 30
```

@smallwinterfeng  一样
