### ISSUE TITLE
1.6 运行前端程序报错 ERROR in Cannot read property 'loadChildren' of null

### ISSUE THREAD

**Issue by chenpfeisoo** [Qihoo360/wayne#510]
**Describe the bug**
1.6版本 前端代码 
运行 make run-frontend
报错

ERROR in Cannot read property 'loadChildren' of null
![image](https://user-images.githubusercontent.com/18147157/68565785-794ac880-048f-11ea-94b8-f68db9c9d3ad.png)

**Comment by chenpfeisoo** [comment]
官方帮忙看看是什么问题？

**Comment by ZhangShiy** [comment]
插件没下

**Comment by chenpfeisoo** [comment]
你好 是什么插件没下载 ？make run-frontend的时候不会自动下载吗 ？  我重试过不行， 如果需要手动下载 ，我该怎么操作 ？

**Comment by ZhangShiy** [comment]
> 你好 是什么插件没下载 ？make run-frontend的时候不会自动下载吗 ？ 我重试过不行， 如果需要手动下载 ，我该怎么操作 ？
https://github.com/Qihoo360/wayne-frontend-plugins

**Comment by chenpfeisoo** [comment]
ok ,我再试试

**Comment by 70data** [comment]
插件下载问题 需要下载前端插件
