### ISSUE TITLE
wayne 是否支持 多系统单点登录

### ISSUE THREAD

**Issue by chenpfeisoo** [Qihoo360/wayne#511]
k8s 生态有很多子系统， 日志。 监控， CI/CD ，微服务相关 的 流量查看， 链路跟踪 等等， 多个系统之间 来回切换访问不是很方便 ， 请问 wayne 有没有实现「或者将要做」类似 单点登录的能力， wayne上登录 实现所有k8s相关系统的权限认证 ，可以免密码登录访问服务。

这个过程应该是要对原始各个子系统进行认证模块改造的 ， 我目前没有相关思路，  官方能大概说说么？

**Comment by motecshine** [comment]
https://github.com/Qihoo360/wayne/blob/99c7e7e5752192791da10ad16f1701a59db82446/src/backend/controllers/auth/authenticator.go

**Comment by chenpfeisoo** [comment]
感谢官方回复， 那意思是要对各个子系统屏蔽原始的认证模块，都走自定义oauth2鉴权是吧
