### ISSUE TITLE
集群原本部署的deployment等，如何导入到对应部门列表

### ISSUE THREAD

**Issue by YanbingW** [Qihoo360/wayne#512]
集群在使用wayne管理之前，已经部署有应用。使用wayne平台之后，之前已有的部署应用是否可以关联到已有部门？

如果现有功能不可以满足这个需求，请问是否有改进的方法？谢谢！

**Comment by 70data** [comment]
请参考 手动应用迁移
https://360yun.org/wayne/migration/manual-migration.html
