### ISSUE TITLE
1.8.4 版本前端创建配置集报错

### ISSUE THREAD

**Issue by 2210635870** [Qihoo360/wayne#515]
**前端创建配置集报错**
点击配置集菜单，右上角弹出无信息错误提示框。
chrome 浏览器 f12 工具调试发现 /api/v1/apps/2/configmaps/tpls 的调用返回404 错误

**Server Version**
```
- Kubernetes version: 1.13.1
- Wayne version:1.8.4

```

**Comment by 2210635870** [comment]
补充，通过k8s 部署的，应该是 q8sio/wayne-backend:v1.8.4-16-gf3a7366 或者 q8sio/wayne-frontend:latest 镜像有问题。

**Comment by qikaih** [comment]
+1

**Comment by 70data** [comment]
已解决

**Comment by ndaysy** [comment]
请问怎么解决的，升级前端还是后端，还是要都升级？

**Comment by 70data** [comment]
只升级后端即可。
或者等我们春节前发一个新版。
