### ISSUE TITLE
wayne backend 1.8.4 websocket 3秒自动断开

### ISSUE THREAD

**Issue by tzm1921995** [Qihoo360/wayne#516]
进入后台管理kubernetes集群，直接web登录pod时 websocket断开太快，只要三秒无输入就会自动断开

**Comment by 70data** [comment]
kubernetes版本是什么
是否有更多的报错截图及日志

**Comment by futianshi1314** [comment]
我们自己在做webshell，但是遇到一个问题，如果残留了bash进程在容器内 重启pod或者滚动升级时候旧的pod会无法正常终止 产生很多bash或者runc的僵尸进程 咱们源码在哪部分 想借鉴下

**Comment by MirrorTown** [comment]
这个很可能和楼主nginx是否有配置websocket支持有关
