### ISSUE TITLE
创建k8s集群报错

### ISSUE THREAD

**Issue by YanbingW** [Qihoo360/wayne#521]
**Describe the bug**
使用开发者模式启动前端和后端，运行正常。关联集群以后，显示错误，后端运行失败

[ORM]2019/12/04 11:12:45 unsupport orm tag namespace
2019/12/04 11:12:45.931 [E] [newhook.go:70]  EventBus 未初始化
2019/12/04 11:12:45.951 [I] [asm_amd64.s:1333]  http server Running on http://:8080
2019/12/04 11:12:45.952 [I] [asm_amd64.s:1333]  Admin server Running on :8088
E1204 11:12:45.955202   18914 runtime.go:78] Observed a panic: "assignment to entry in nil map                                                                       " (assignment to entry in nil map)
goroutine 37 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x178ab20, 0x1c09670)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xaa
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x178ab20, 0x1c09670)
        /root/go/go/src/runtime/panic.go:513 +0x1b9
k8s.io/client-go/tools/clientcmd/api/v1.Convert_Slice_v1_NamedCluster_To_Map_string_To_Pointer                                                                       _api_Cluster(0xc0001443b0, 0xc000fba1b0, 0x1c377a0, 0xc000efa0f0, 0x0, 0x0)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go:35 +                                                                       0x1e9
k8s.io/client-go/tools/clientcmd/api/v1.autoConvert_v1_Config_To_api_Config(0xc000144370, 0xc0                                                                       00fba180, 0x1c377a0, 0xc000efa0f0, 0x2d59e5684a455b01, 0xc0006af558)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conve                                                                       rsion.go:273 +0xa0
k8s.io/client-go/tools/clientcmd/api/v1.Convert_v1_Config_To_api_Config(0xc000144370, 0xc000fb                                                                       a180, 0x1c377a0, 0xc000efa0f0, 0x161f3e0, 0xc0002d5320)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conve                                                                       rsion.go:291 +0x49
k8s.io/client-go/tools/clientcmd/api/v1.RegisterConversions.func7(0x182b5e0, 0xc000144370, 0x1                                                                       82b520, 0xc000fba180, 0x1c377a0, 0xc000efa0f0, 0x203000, 0xc0004ca000)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conve                                                                       rsion.go:69 +0x6f
k8s.io/apimachinery/pkg/conversion.(*Converter).doConversion(0xc0002aa3c0, 0x182b5e0, 0xc00014                                                                       4370, 0x182b520, 0xc000fba180, 0x0, 0xc00053af60, 0xc0006af738, 0xd300000000000020, 0x1807380)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/conversion/converter.go:498 +0x6d4
k8s.io/apimachinery/pkg/conversion.(*Converter).Convert(0xc0002aa3c0, 0x182b5e0, 0xc000144370,                                                                        0x182b520, 0xc000fba180, 0x0, 0xc00053af60, 0x1c18860, 0xc000fba180)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/conversion/converter.go:470 +0x9d
k8s.io/apimachinery/pkg/runtime.(*Scheme).convertToVersion(0xc0003189a0, 0xc0006afc01, 0x1c188                                                                       e0, 0xc0001442c0, 0x1c19fe0, 0xc00053af20, 0x2b93c60, 0xc00053af20, 0xc00053af20, 0x189bea0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/runtime/scheme.go:566 +0xa10
k8s.io/apimachinery/pkg/runtime.(*Scheme).ConvertToVersion(0xc0003189a0, 0x1c188e0, 0xc0001442                                                                       c0, 0x1c19fe0, 0xc00053af20, 0x0, 0x0, 0xc000c8bd00, 0x40d91f)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/runtime/scheme.go:486 +0x5f
github.com/Qihoo360/wayne/src/backend/client.buildClient(0xc00052a450, 0xb, 0xc000b57800, 0x15                                                                       65, 0x0, 0x0, 0x0, 0x0)
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/client/client.go:195                                                                        +0x1d7
github.com/Qihoo360/wayne/src/backend/client.BuildApiserverClient()
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/client/client.go:69                                                                        +0x21b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x1a93e90)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1a93e90, 0x12a05f200, 0x0, 0x1, 0xc0000ea600)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xbe
k8s.io/apimachinery/pkg/util/wait.Until(0x1a93e90, 0x12a05f200, 0xc0000ea600)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
k8s.io/apimachinery/pkg/util/wait.Forever(0x1a93e90, 0x12a05f200)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:79 +0x41
created by github.com/Qihoo360/wayne/src/backend/initial.InitClient
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/initial/client.go:13                                                                        +0x50
panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map

goroutine 37 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x108
panic(0x178ab20, 0x1c09670)
        /root/go/go/src/runtime/panic.go:513 +0x1b9
k8s.io/client-go/tools/clientcmd/api/v1.Convert_Slice_v1_NamedCluster_To_Map_string_To_Pointer                                                                       _api_Cluster(0xc0001443b0, 0xc000fba1b0, 0x1c377a0, 0xc000efa0f0, 0x0, 0x0)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/conversion.go:35 +                                                                       0x1e9
k8s.io/client-go/tools/clientcmd/api/v1.autoConvert_v1_Config_To_api_Config(0xc000144370, 0xc0                                                                       00fba180, 0x1c377a0, 0xc000efa0f0, 0x2d59e5684a455b01, 0xc0006af558)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conve                                                                       rsion.go:273 +0xa0
k8s.io/client-go/tools/clientcmd/api/v1.Convert_v1_Config_To_api_Config(0xc000144370, 0xc000fb                                                                       a180, 0x1c377a0, 0xc000efa0f0, 0x161f3e0, 0xc0002d5320)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conve                                                                       rsion.go:291 +0x49
k8s.io/client-go/tools/clientcmd/api/v1.RegisterConversions.func7(0x182b5e0, 0xc000144370, 0x1                                                                       82b520, 0xc000fba180, 0x1c377a0, 0xc000efa0f0, 0x203000, 0xc0004ca000)
        /root/workspaces/gopath/src/k8s.io/client-go/tools/clientcmd/api/v1/zz_generated.conve                                                                       rsion.go:69 +0x6f
k8s.io/apimachinery/pkg/conversion.(*Converter).doConversion(0xc0002aa3c0, 0x182b5e0, 0xc00014                                                                       4370, 0x182b520, 0xc000fba180, 0x0, 0xc00053af60, 0xc0006af738, 0xd300000000000020, 0x1807380)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/conversion/converter.go:498 +0x6d4
k8s.io/apimachinery/pkg/conversion.(*Converter).Convert(0xc0002aa3c0, 0x182b5e0, 0xc000144370,                                                                        0x182b520, 0xc000fba180, 0x0, 0xc00053af60, 0x1c18860, 0xc000fba180)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/conversion/converter.go:470 +0x9d
k8s.io/apimachinery/pkg/runtime.(*Scheme).convertToVersion(0xc0003189a0, 0xc0006afc01, 0x1c188                                                                       e0, 0xc0001442c0, 0x1c19fe0, 0xc00053af20, 0x2b93c60, 0xc00053af20, 0xc00053af20, 0x189bea0)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/runtime/scheme.go:566 +0xa10
k8s.io/apimachinery/pkg/runtime.(*Scheme).ConvertToVersion(0xc0003189a0, 0x1c188e0, 0xc0001442                                                                       c0, 0x1c19fe0, 0xc00053af20, 0x0, 0x0, 0xc000c8bd00, 0x40d91f)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/runtime/scheme.go:486 +0x5f
github.com/Qihoo360/wayne/src/backend/client.buildClient(0xc00052a450, 0xb, 0xc000b57800, 0x15                                                                       65, 0x0, 0x0, 0x0, 0x0)
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/client/client.go:195                                                                        +0x1d7
github.com/Qihoo360/wayne/src/backend/client.BuildApiserverClient()
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/client/client.go:69                                                                        +0x21b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x1a93e90)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1a93e90, 0x12a05f200, 0x0, 0x1, 0xc0000ea600)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xbe
k8s.io/apimachinery/pkg/util/wait.Until(0x1a93e90, 0x12a05f200, 0xc0000ea600)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
k8s.io/apimachinery/pkg/util/wait.Forever(0x1a93e90, 0x12a05f200)
        /root/workspaces/gopath/src/k8s.io/apimachinery/pkg/util/wait/wait.go:79 +0x41
created by github.com/Qihoo360/wayne/src/backend/initial.InitClient
        /root/workspaces/gopath/src/github.com/Qihoo360/wayne/src/backend/initial/client.go:13                                                                        +0x50
exit status 2

**Comment by 70data** [comment]
已修复
