### ISSUE TITLE
版本支持问题

### ISSUE THREAD

**Issue by 20062914** [Qihoo360/wayne#522]
最新的k8s版本为1.17.x 然而backend程序中使用的client-go版本是11 和最新的版本不兼容，导致无法在前台发布deployment，能不能提供一下解决方案？我试着init 低版本的k8s但是也没有成功

**Comment by 70data** [comment]
目前最高支持 1.15版本
后续版本监控在开发中

**Comment by daigong** [comment]
Hello，版本支持有最新进展么？麻烦啦

**Comment by ody123** [comment]
> Hello，版本支持有最新进展么？麻烦啦

同问😕

**Comment by leucene** [comment]
> > Hello，版本支持有最新进展么？麻烦啦
> 
> 同问😕

Any update pls tell  us.

**Comment by daigong** [comment]
> > > Hello，版本支持有最新进展么？麻烦啦
> > 
> > 
> > 同问😕
> 
> Any update pls tell us.

3Q，Urge more 。。

**Comment by leucene** [comment]
这个是为啥？










在 2020-04-29 11:02:32，"ReiDai" <notifications@github.com> 写道：

Hello，版本支持有最新进展么？麻烦啦

同问

Any update pls tell us.

3Q，Urge more 。。

**Comment by 70data** [comment]
Has supported https://github.com/Qihoo360/wayne/pull/565.
