### ISSUE TITLE
镜像版本问题

### ISSUE THREAD

**Issue by dingmingk** [Qihoo360/wayne#526]
Error response from daemon: manifest for 360cloud/wayne-backend:v1.8.4-16-gf3a7366 not found

最新的配置文件里的版本，镜像仓库里没有无法拉取。

**Comment by qianarcher** [comment]
一样的报错，最近的一次更新改了docker源，不知道是不是这个不能访问导致的

**Comment by qianarcher** [comment]
去看了各大镜像网站，这个镜像最近一次的更新都是三个月前tag也是1.8，用了latest版本启动不了，应该是镜像没更新的问题。

**Comment by chenpfeisoo** [comment]
+1

**Comment by 70data** [comment]
春节前我们会传一个新版镜像以及一个新的版本。
