### ISSUE TITLE
Master版本无法初始化plugins

### ISSUE THREAD

**Issue by wefanWes** [Qihoo360/wayne#527]
Master版本plugins @ 360e7ce，点击进去显示404，更新的时候显示：
`wayne git:(master) ✗ git submodule update --init --recursive
error: Server does not allow request for unadvertised object 360e7cea4e4f37a9ae64fc1f80ec9fac0cf22f32
Fetched in submodule path 'src/backend/plugins', but it did not contain 360e7cea4e4f37a9ae64fc1f80ec9fac0cf22f32. Direct fetching of that commit failed.`

1.8.5版本的是plugins @ 9d23dac，能点进去。

是否忘了提交submodule ？360e7cea4e4f37a9ae64fc1f80ec9fac0cf22f32

**Comment by jxhsjxhs** [comment]
我咋感觉他们不想做了。。。。

**Comment by fate-node** [comment]
感觉很敷衍...4天前的错误

**Comment by YanbingW** [comment]
一个笨方法，可以切换到其他版本，再初始化插件，初始化以后再切换回来

**Comment by luolizhi** [comment]
更新迭代不动明显慢了，

**Comment by luolizhi** [comment]
更新明显慢下来了，

**Comment by 70data** [comment]
我们发布了新版本 https://github.com/Qihoo360/wayne/releases/tag/v1.8.6
请看看是否还有这个问题。
