### ISSUE TITLE
部署失败问题

### ISSUE THREAD

**Issue by jxhsjxhs** [Qihoo360/wayne#528]
各位大哥。问几个问题
1.现在最新版本(1.8.5部署有问题) 我checkout到其他版本比如 1.7 发现用的镜像是latest...建议各位大佬以后不要用latest 不然更新完版本以后老版本已经不可用了。
2.各位大佬对这个项目态度是啥呢。。内部试水的还是。能外部人员PR不。

**Comment by fate-node** [comment]
我就想知道你说的PR 什么缩写？

**Comment by jxhsjxhs** [comment]
> 我就想知道你说的PR 什么缩写？

Pull requests ?

**Comment by 70data** [comment]
1. 我们会在春节前重新发布一个新版以及并推送一个新的镜像。
2. 内部早已大规模使用。欢迎提pr，contributor里大部分人是非公司成员。

**Comment by 70data** [comment]
我们已经发了新的版本。
https://github.com/Qihoo360/wayne/releases/tag/v1.8.6

**Comment by 70data** [comment]
如果有兴趣参与开发可以联系我。
