### ISSUE TITLE
升级backend后，db的字段如何更新？

### ISSUE THREAD

**Issue by wefanWes** [Qihoo360/wayne#532]
项目在老版本使用一段时间后mysql已经有了不少数据，想升级到新的版本。当前在k8s升级backend镜像之后，mysql里头的字段并没有随着新版本一起升级，导致backend运行频繁报字段没找见，前端页面点击项目会无限404.

请问如何在不删除当前mysql数据的情况下，升级backend？或者怎么整出sql语句，得到当前需要更新哪些字段。。

**Comment by 70data** [comment]
春节前我们会传一个新版镜像以及一个新的版本

**Comment by 70data** [comment]
see this https://github.com/Qihoo360/wayne/issues/536
