### ISSUE TITLE
please update k8s client go version

### ISSUE THREAD

**Issue by guobayang** [Qihoo360/wayne#534]
wayne shows error " Failed to list *v1beta1.Deployment: the server could not find the requested resource".
our kubernetes version is v1.16.4

**Comment by jemygraw** [comment]
```
apps_v1beta1 "k8s.io/api/apps/v1beta1"
```

是这个路径。

**Comment by zhoudshu** [comment]
我也出现相同的问题了， our kubernetes version is v1.17.0

**Comment by 70data** [comment]
See this. https://github.com/Qihoo360/wayne/issues/501
Now, wayne isn't support k8s 1.16 or later.
The logic of template need update mysql table.Have some hardcode in it.

**Comment by zhangyuming** [comment]
计划 什么时候解决该问题呢？ @70data

**Comment by 70data** [comment]
目前维护该项目的时间有限，如果您有意向可以，一起协同开发。
