### ISSUE TITLE
修改副本数成功后，在克隆发版或者api克隆发版时副本数未生效

### ISSUE THREAD

**Issue by newyue588cc** [Qihoo360/wayne#547]
**Describe the bug**
1.8.6新增修改副本数功能，在此功能中，修改副本数扩容可以正常扩容完成。不过在后续发版中发现，扩容后的副本数未继承到克隆后的模板中，使用openapi也是同样的结果。

**Expected behavior**
在修改副本数后，新的副本数值应该继承到模板中，在克隆或者api发版时均是新的副本数。

**Screenshots**
![image](https://user-images.githubusercontent.com/3349048/74904038-bfe08500-53e5-11ea-90ed-6b0cf8fb069b.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome

**Server Version**
```
- Kubernetes version: 1.13
- Wayne version: v1.8.6
```

**Additional context**
上面截图为在wayne上操作的结果。另外，在使用openapi操作也是同样的问题。

**Comment by 70data** [comment]
目前的逻辑是，需要部署一栏修改副本数才会全局生效。
针对模版的操作，仅针对模版生效。

**Comment by newyue588cc** [comment]
这个逻辑是修改副本数功能只针对当前模板，如果克隆了模板后，生成新的模板，上面修改副本数的操作就会失效，必须重新操作才可以生效，不知道我的理解是否正确，谢谢。

**Comment by newyue588cc** [comment]
我理解了，这里的逻辑是只能从编辑部署的地方可以修改全局副本数；  而新增加的修改副本数功能只是用来针对当前模板的临时扩容。2个地方结合修改，可以达到想要的目的。

**Comment by 70data** [comment]
![image](https://user-images.githubusercontent.com/6611594/75211724-d872e580-57bf-11ea-8d3e-024a3d07409d.png)

**Comment by newyue588cc** [comment]
理解，谢谢。就是问下，这个逻辑未来可以让2个地方关联起来吗？就是在修改副本数以后，这个值会替换掉编辑部署里面的副本数，达到相互的关联。业务操作上来说，我们通常不会去做编辑部署，前面做扩容是直接克隆发版，在点发版时修改副本数。
