### ISSUE TITLE
OpenAPI方式 使用CI/CD 中的集成升级部署不生效

### ISSUE THREAD

**Issue by zhaolei0914** [Qihoo360/wayne#550]
dockercompose方式部署在centos7.4
调用OpenApi接口upgrade_deployment更新部署的镜像，没有报错但是部署项目的镜像地址和镜像的参数没有变化

**Comment by 70data** [comment]
能否提供详细的调用方式（参数）与信息？

**Comment by zhaolei0914** [comment]
按照模板id去升级部署，镜像地址和环境变量没有变化


![企业微信截图_15840001959249](https://user-images.githubusercontent.com/7426709/76500155-01ab9b00-647b-11ea-9686-67b10efcaa11.png)
![企业微信截图_158400017322](https://user-images.githubusercontent.com/7426709/76500158-02dcc800-647b-11ea-96f7-e73740a1ef74.png)

**Comment by MirrorTown** [comment]
你在wayne上点击发布后 前端会经过一段代码渲染deployment再给后端(带上最新的版本信息)，不知道你再调用的时候是否有处理
