### ISSUE TITLE
wayne-backend 后端部署失败

### ISSUE THREAD

**Issue by DreamsMan** [Qihoo360/wayne#552]
wayne-backend-76c96c7667         0/1     Error 
![image](https://user-images.githubusercontent.com/35064168/76846843-1bceea00-687c-11ea-91c1-909b2beb06f9.png)

**Comment by 70data** [comment]
请提供详细的日志即报错信息
多谢

**Comment by YWliyage** [comment]
![image](https://user-images.githubusercontent.com/35064168/76853354-0cee3480-6888-11ea-8a7d-9a886aaff929.png)
感谢！

**Comment by YWliyage** [comment]
> ![image](https://user-images.githubusercontent.com/35064168/76853354-0cee3480-6888-11ea-8a7d-9a886aaff929.png)
> 感谢！

![image](https://user-images.githubusercontent.com/35064168/76855233-ae2aba00-688b-11ea-8f05-04c114f0fea0.png)

**Comment by YWliyage** [comment]
![image](https://user-images.githubusercontent.com/35064168/76855446-1f6a6d00-688c-11ea-8bc6-f821ea95b7d1.png)

**Comment by 70data** [comment]
看报错是数据库连不上。

**Comment by YWliyage** [comment]
感谢
