### ISSUE TITLE
管理员后台看不到集群任何信息

### ISSUE THREAD

**Issue by DreamsGo** [Qihoo360/wayne#554]
![image](https://user-images.githubusercontent.com/58097453/76952154-a3cdf600-6947-11ea-97f4-ab769ee3cd5e.png)
![image](https://user-images.githubusercontent.com/58097453/76952526-32427780-6948-11ea-8308-9fb077bc98df.png)

**Comment by 70data** [comment]
默认添加集群了么？
什么k8s版本？

**Comment by death9394** [comment]
关联了k8s集群了没？
管理员后台-集群-列表-关联集群
Master要填对，参考https://blog.csdn.net/qq_42006894/article/details/87259171
