### ISSUE TITLE
部署wayne在k8s集群上，如何让前端通过cluster IP访问后端

### ISSUE THREAD

**Issue by YanbingW** [Qihoo360/wayne#555]
咨询一个问题，谢谢！
现在的k8s部署文件中，前端访问后端，是通过后端暴露的node Port前端才得以访问，
如果我不想暴露后端端口，怎么才能让前端通过clusterIP+port访问后端呢？
是不是需要修改一下前端代码？

多谢指教！

**Comment by MirrorTown** [comment]
在源码里有wayne-backend的Service可以提供clusterIP+port方式使用

**Comment by YanbingW** [comment]
> 提供

后端端口修改问题不大，现在的问题是前端怎么访问后端？
如何修改config.js文件？
如果修改为
后端：
cluster IP 8080
前端config.js
URL：127.0.0.1:8080
这样会报跨域错误

**Comment by MirrorTown** [comment]
域名和前端用同一个，通过location区分转发策略

**Comment by YanbingW** [comment]
同一台机器编译前后端的过程中就有这个问题： config.js中的url设置为localhost或者127.0.0.1加端口都会报跨域错误。 只有把url改为真实ip才不会报错。 ------------------ 原始邮件 ------------------
发件人: "MirrorTown"<notifications@github.com>
发送时间: 2020年3月27日(星期五) 下午3:21
收件人: "Qihoo360/wayne"<wayne@noreply.github.com>;
抄送: "YanbingW"<280808267@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Qihoo360/wayne] 部署wayne在k8s集群上，如何让前端通过cluster IP访问后端 (#555)




 
域名和前端用同一个，通过location区分转发策略
 
&mdash;

**Comment by 70data** [comment]
config.js中的url需要浏览器可以访问才行。
