### ISSUE TITLE
k8s中安装成功后访问首页报错

### ISSUE THREAD

**Issue by Jeremy-boo** [Qihoo360/wayne#556]
**Describe the bug**
在k8s中部署后，访问首页，页面没有加载出来
页面报错内容如下
![image](https://user-images.githubusercontent.com/41532403/78647784-9fb14a80-78ed-11ea-8457-0877a3eb142d.png)

**Server Version**
```
拉取的master分支内容，里面镜像内容都为：360cloud/wayne-frontend:latest，360cloud/wayne-frontend:latest
- Dashboard version: 
- Kubernetes version:  v1.15.3
- Wayne version:   
- Go version:
```

**Additional context**
请问是k8s运行时候，waye-frontend.yaml中配置文件需要改动吗？

**Comment by Jeremy-boo** [comment]
waye-frontend.yaml 中需要手动配置nodeIp

**Comment by prasenforu** [comment]
@Jeremy-boo 

Not working with service DNS.

```
  config.js: |-
    window.CONFIG = {
      URL: 'http://wayne-backend.default.svc.cluster.local:8080',
      RAVEN: false,
      RAVEN_DSN: 'RAVEN_DSN'
    };

```

**Comment by xiahuhu1** [comment]
这个问题解决了吗，怎么关闭了？

**Comment by Jeremy-boo** [comment]
通过手动配置node ip已经解决了，谢谢关注

**Comment by Jeremy-boo** [comment]
> 这个问题解决了吗，怎么关闭了？

**Comment by Jeremy-boo** [comment]
> 这个问题解决了吗，怎么关闭了？

通过手动配置node ip 已经解决了，谢谢关注
