### ISSUE TITLE
Wayne API - CronJob 是否支持 Api 接口调用方式部署

### ISSUE THREAD

**Issue by zongkaixuan** [Qihoo360/wayne#559]
Hi，
我看了一下 Wayne 的 API 资料，发现 Deployment 是支持通过 API 实现部署的。请问 CronJob 支持这种 API 调用的方式触发部署吗？

Thanks，

**Comment by 70data** [comment]
目前不支持

**Comment by h1z3y3** [comment]
Wayne API 还不支持获取deployment正在运行的 template 信息，
只能获取最新版本的template（可能不在线上）
