### ISSUE TITLE
后端镜像下载不了，为甚么？

### ISSUE THREAD

**Issue by sakufo** [Qihoo360/wayne#560]
Events:
  Type     Reason          Age                From               Message
  ----     ------          ----               ----               -------
  Normal   Scheduled       <unknown>          default-scheduler  Successfully assigned default/wayne-backend-5fd6867c48-hd76r to k3
  Normal   Pulling         22s                kubelet, k3        Pulling image "360cloud/wayne-backend:v1.8.4-16-gf3a7366"
  Warning  Failed          15s                kubelet, k3        Failed to pull image "360cloud/wayne-backend:v1.8.4-16-gf3a7366": rpc error: code = Unknown desc = Error response from daemon: manifest for 360cloud/wayne-backend:v1.8.4-16-gf3a7366 not found
  Warning  Failed          15s                kubelet, k3        Error: ErrImagePull
  Normal   SandboxChanged  14s                kubelet, k3        Pod sandbox changed, it will be killed and re-created.
  Normal   BackOff         12s (x3 over 13s)  kubelet, k3        Back-off pulling image "360cloud/wayne-backend:v1.8.4-16-gf3a7366"
  Warning  Failed          12s (x3 over 13s)  kubelet, k3        Error: ImagePullBackOff
[root@k1 kubernetes]# docker pull 360cloud/wayne-backend:v1.8.4-16-gf3a7366
Error response from daemon: manifest for 360cloud/wayne-backend:v1.8.4-16-gf3a7366 not found

**Comment by 70data** [comment]
用最新版镜像试试？
