### ISSUE TITLE
docker pull 360cloud/wayne-backend:v1.8.4-16-gf3a7366 Error response from daemon: manifest for 360cloud/wayne-backend:v1.8.4-16-gf3a7366 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by pi-pi-miao** [Qihoo360/wayne#566]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by 70data** [comment]
请拉最新的镜像版本试试。

**Comment by pi-pi-miao** [comment]
> 请拉取最新的适当版本尝试。
我的意思是yaml文件中的你们修改呗，另外我拉取最新的了，首次访问4200是空白页
