### ISSUE TITLE
按照readme访问页面空白进不去

### ISSUE THREAD

**Issue by pi-pi-miao** [Qihoo360/wayne#567]
使用的go版本：1.14
使用的docker版本：19.03.4
使用的k8s版本为：1.17.2

访问日志
wayne-frontend_1  | 172.17.0.1 - - [12/Jun/2020:19:31:18 +0800] "GET / HTTP/1.1" 200 833 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [12/Jun/2020:19:31:18 +0800] "GET /config.js?v=1 HTTP/1.1" 200 97 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [12/Jun/2020:19:31:18 +0800] "GET /polyfills.d90c14f171c836065b38.js HTTP/1.1" 200 57419 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [12/Jun/2020:19:31:18 +0800] "GET /runtime.465c2333d355155ec5f3.js HTTP/1.1" 200 1440 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [12/Jun/2020:19:31:18 +0800] "GET /scripts.de201845a2731569a1ce.js HTTP/1.1" 200 708250 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [12/Jun/2020:19:31:18 +0800] "GET /styles.0a34fe80ace344988981.css HTTP/1.1" 200 434886 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [12/Jun/2020:19:31:18 +0800] "GET /vendor.fa948cd7d1e16632625c.js HTTP/1.1" 200 3373841 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [12/Jun/2020:19:31:18 +0800] "GET /main.7f0a9de62f40b2ffdf62.js HTTP/1.1" 200 4549328 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [12/Jun/2020:19:31:19 +0800] "GET /assets/images/icon.png HTTP/1.1" 200 41719 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [12/Jun/2020:19:31:25 +0800] "GET /assets/i18n/zh-Hans.json?v=1.8.5 HTTP/1.1" 200 28541 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

**Comment by ksmiracle** [comment]
我之前也遇到过类似的情况 建议你看下后端的日志 是不是和库链接有问题

**Comment by 70data** [comment]
请检查前后端通信问题。

**Comment by pi-pi-miao** [comment]
> 我之前也遇到过类似的情况建议你看下一段的日志是不是和库链接有问题
我是根据readme使用docke-compose 启动的，应该没有问题
