### ISSUE TITLE
docker-compose -f docker-compose up然后登录浏览器不显示

### ISSUE THREAD

**Issue by pi-pi-miao** [Qihoo360/wayne#568]
![image](https://user-images.githubusercontent.com/27882151/84582363-9a0c3f80-ae1d-11ea-9492-060f4f3b8481.png)
日志
x x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:56:22 +0800] "GET /config.js?v=1 HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:56:22 +0800] "GET /main.7f0a9de62f40b2ffdf62.js HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:56:22 +0800] "GET /polyfills.d90c14f171c836065b38.js HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:56:22 +0800] "GET /runtime.465c2333d355155ec5f3.js HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:56:22 +0800] "GET /styles.0a34fe80ace344988981.css HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:56:22 +0800] "GET /vendor.fa948cd7d1e16632625c.js HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:56:22 +0800] "GET /scripts.de201845a2731569a1ce.js HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:58:52 +0800] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:58:52 +0800] "GET /styles.0a34fe80ace344988981.css HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:58:52 +0800] "GET /config.js?v=1 HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:58:52 +0800] "GET /scripts.de201845a2731569a1ce.js HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:58:52 +0800] "GET /polyfills.d90c14f171c836065b38.js HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:58:52 +0800] "GET /runtime.465c2333d355155ec5f3.js HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:58:52 +0800] "GET /main.7f0a9de62f40b2ffdf62.js HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
wayne-frontend_1  | 172.17.0.1 - - [14/Jun/2020:08:58:52 +0800] "GET /vendor.fa948cd7d1e16632625c.js HTTP/1.1" 304 0 "http://127.0.0.1:4200/" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

**Comment by pi-pi-miao** [comment]
![image](https://user-images.githubusercontent.com/27882151/84582371-caec7480-ae1d-11ea-98f4-66f2e5a07f19.png)

**Comment by 70data** [comment]
浏览器按 F12，看一下是否访问异常的情况。
同时检查一下后端服务的各个配置是否正确。
