### ISSUE TITLE
不应该把密码和用户名放在url里

### ISSUE THREAD

**Issue by zhangguanzhang** [Qihoo360/wayne#577]
```
 'http://10.0.23.29:8080/login/db?username=admin&password=zhangguanzhang'
```
https://github.com/Qihoo360/wayne/blob/98197fc02bc52e4b45e6b90acb9496d24c72f9c9/src/backend/controllers/auth/authenticator.go#L59-L60

https://github.com/Qihoo360/wayne/blob/98197fc02bc52e4b45e6b90acb9496d24c72f9c9/src/frontend/src/app/shared/client/v1/auth.service.ts#L18

**Comment by EverCurse** [comment]
docker 版本好像登录报错400了

**Comment by EverCurse** [comment]
![image](https://user-images.githubusercontent.com/12572050/89141001-dc2c4480-d575-11ea-9dd1-c2b1e54fccfb.png)

**Comment by zhangguanzhang** [comment]
前端镜像没更新的原因
