### ISSUE TITLE
tf serving RESTful API  Ingress 路由路径

### ISSUE THREAD

**Issue by LYU2026** [Qihoo360/wayne#590]
tensorflow serving restful api 的默认端口是8501，在终端使用命令curl http://localhost:8501/v1/models/模型名。
需要在Ingress配置路由路径到 容器内部：域名+路由路径——> http://localhost:8501/v1/models/模型名:predict
映射了8501到域名服务器的80端口。后面的路由路径、Ingress怎么配置呢？谢谢

**Comment by 70data** [comment]
请参看k8s官方文档。
