### ISSUE TITLE
kubernetes 部署方式，wayne-backend.yaml 中的版本在hub.docker.com中不存在

### ISSUE THREAD

**Issue by gotoworld** [Qihoo360/wayne#593]
**Describe the bug**
`Failed to pull image "360cloud/wayne-backend:v1.8.4-16-gf3a7366": rpc error: code = Unknown desc = Error response from daemon: manifest for 360cloud/wayne-backend:v1.8.4-16-gf3a7366 not found`

**To Reproduce**
`kubectl apply -f wayne-backend.yaml`

**Expected behavior**
no image pull error

**Screenshots**
![image](https://user-images.githubusercontent.com/8605471/89257744-5f729680-d659-11ea-807a-69e95f1c550a.png)

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by 70data** [comment]
Thanks.
https://github.com/Qihoo360/wayne/pull/594
