### ISSUE TITLE
访问127.0.0.1:4200空白是什么原因？

### ISSUE THREAD

**Issue by 19774279** [Qihoo360/wayne#614]
127.0.0.1:4200访问是空白，但是浏览器的标签栏可以看到wayne的那个云朵图标和Wayne字样，127.0.0.1:8080是一个power by beego的404页面。用`docker-compose -f ./hack/docker-compose/docker-compose.yaml up`启动的，可以看到大量的建表语句，命令行页面没看到什么错误。
后台可以看到这样的日志

> [I] [asm_amd64.s:1337]http server Running on http://:8080
> [I] [asm_amd64.s:1337]Admin server Running on :8088

系统是CentOS 7.9，没有装k8s。

**Comment by 19774279** [comment]
docker-compose温机哪家下面有个配置文件，里面有yourip:8080，把yourip改成本地ip就好了。不过现在用户名密码错误，还在找原因

**Comment by yooshijie** [comment]
[root@dh-k8s-master conf]# pwd
/opt/wayne/wayne/hack/docker-compose/conf
[root@dh-k8s-master conf]# ls
app.conf  config.js
[root@dh-k8s-master conf]# cat config.js 
window.CONFIG = {
    URL: 'http://192.168.109.5:8080',
    RAVEN: false,
    RAVEN_DSN: 'RAVEN_DSN'
};
[root@dh-k8s-master conf]# 
修改过之后依然不行。
![image](https://user-images.githubusercontent.com/22093770/112562398-24082080-8e12-11eb-891a-05f781f02723.png)
