### ISSUE TITLE
migration from exist kubernetes clusters

### ISSUE THREAD

**Issue by wilhelmguo** [Qihoo360/wayne#68]
**Is your feature request related to a problem? Please describe.**
user want to migration from exist kubernetes clusters
ex Deployment, Service...

**Describe the solution you'd like**

read all resource form kubernetes, user select one, and click import, then deal labels and auto create resource and tpl.

**Comment by xinyuanyu** [comment]
Got the same problem when deploying wayne to existing kubernetes cluster.
