### ISSUE TITLE
panic: dial tcp 127.0.0.1:3306: connect: connection refused

### ISSUE THREAD

**Issue by EyckSDLuo** [Qihoo360/wayne#75]
我在本地mysql上创建了一个wayne数据库，但是在执行docker-compose up wayne还是遇到这个问题，请问怎么解决

![image](https://user-images.githubusercontent.com/20282930/49074708-38eb3e00-f270-11e8-81f8-609edd5bc7bf.png)
![image](https://user-images.githubusercontent.com/20282930/49074721-41437900-f270-11e8-8091-ecb12e12736e.png)
![image](https://user-images.githubusercontent.com/20282930/49074737-47395a00-f270-11e8-81e7-031120bee0d1.png)

**Comment by wilhelmguo** [comment]
![image](https://user-images.githubusercontent.com/12826425/49077591-9c786a00-f276-11e8-8f13-2edab68cf517.png)

Don't use 127.0.0.1

**Comment by EyckSDLuo** [comment]
我试过localhost和ip地址。都是一样的错误
