### ISSUE TITLE
run "go get https://github.com/Qihoo360/wayne " error

### ISSUE THREAD

**Issue by lp-pl** [Qihoo360/wayne#77]
**Describe the bug**
But what I ran was  "go get https://github.com/Qihoo360/wayne"  then I get back this big error message："package https:/github.com/Qihoo360/wayne: "https://" not allowed in import path".

**Suggestion**
My suggestion to this problem is as follows:
Run"go get github.com/Qihoo360/wayne " instead.

**Desktop**
 - OS:[Ubuntu ]
 - Version [16.04LTS]

**Server Version**
- Kubernetes version: v1.11.0
- Go version:go1.11.1 linux/amd64

**Comment by motecshine** [comment]
you should use `github.com/Qihoo360/wayne`

**Comment by wilhelmguo** [comment]
@lp-pl Document errors， you should use go get github.com/Qihoo360/wayne. The document error has been fixed. Ths for your feedback
