### ISSUE TITLE
docker启动不行

### ISSUE THREAD

**Issue by kongxiaocong** [Qihoo360/wayne#8]
启动命令docker run --rm -v /opt/wayne/conf/app.conf:/opt/wayne/conf/app.conf -p 8080:8080 360cloud/wayne /opt/wayne/backend apiserver

报错
[ORM]2018/11/20 02:35:36 register db Ping `default`, invalid DSN: did you forget to escape a param value?
panic: register db Ping `default`, invalid DSN: did you forget to escape a param value?

**Comment by zhanghuidinah** [comment]
@kongxiaocong  你是MAC吧？

**Comment by kongxiaocong** [comment]
Red Hat Enterprise Linux Server release 7.3 (Maipo)

你们要开个QQ群吗

**Comment by wilhelmguo** [comment]
@kongxiaocong 如果是Mac，配置实际ip，不要配置127.0.0.1

**Comment by wilhelmguo** [comment]
@kongxiaocong 有微信群
