### ISSUE TITLE
Cannot read property 'loadChildren' of null

### ISSUE THREAD

**Issue by olivewind** [Qihoo360/wayne#83]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
run `npm run start` ,then see ->
![image](https://user-images.githubusercontent.com/17901361/49196820-7d3d2200-f3c7-11e8-91ed-fa12a7211ed2.png)
angular-cli version ->
![image](https://user-images.githubusercontent.com/17901361/49196864-9f36a480-f3c7-11e8-9a8a-27e4cc3a925e.png)

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by olivewind** [comment]
还没完整看一遍代码，现在看来是因为项目导入了几个在 lib/ 目录下不存在模块？

**Comment by wilhelmguo** [comment]
@olivewind You should init git submodule.   
$ git submodule update --init --recursive 

refer to [https://github.com/Qihoo360/wayne/wiki/Wayne-dev-develop-flow](https://github.com/Qihoo360/wayne/wiki/Wayne-dev-develop-flow)

**Comment by olivewind** [comment]
@wilhelmguo  发现这个问题了，尴尬。

但是我想应该不只我一个开发者(尤其是前端开发者)会遇到这种问题，建议在为 frontend 目录单独编写一份无需安装 Go 的快速启动开发环境的指南

前端开发者应该只需要做两件事:
1. 使用  docker compose 启动后端和数据库服务以提供接口
2. 启动前端 dev server

而现在前端开发者却需要而外安装 go，甚至搞清楚 GO-PATH 的概念。这对前端开发者是不友好的，而刚好这个项目的很大的价值是来自前端提供了 k8s yaml 的可视化操作。
