### ISSUE TITLE
已删除的集群，wayne 还会尝试连接集群

### ISSUE THREAD

**Issue by olivewind** [Qihoo360/wayne#86]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

通过 web-ui 接入集群时候，填错 yaml，导致集群不可达时候，删除该集群
但是  wayne 一直在尝试连接这个已经被删除的集群，重启可以解决

![image](https://user-images.githubusercontent.com/17901361/49225247-873e3f80-f41e-11e8-890f-efe9ffe3c3cf.png)

**Desktop (please complete the following information):**

**Server Version**
```
- Dashboard version:
- Kubernetes version:
- Wayne version:
- Node.js version:
- Go version:
```

**Additional context**

**Comment by wilhelmguo** [comment]
Fix
