### ISSUE TITLE
import package error

### ISSUE THREAD

**Issue by yulibaozi** [Qihoo360/wayne#92]
**Describe the bug**
report "no Go files in $GOPATH/src/github.com/Qihoo360/wayne/src/backend/plugins" when i git clone this repo, i try to git pull this repo Qihoo360/wayne-backend-plugins,but  can't fix this problem。

**To Reproduce**
1. git clone  this repo
2. vscode open this project
3. go run main.go
```
➜  backend git:(master) go run main.go
routers/router.go:50:2: no Go files in GOPATH/src/github.com/Qihoo360/wayne/src/backend/plugins
```
4.  go to dir src/backend/plugins
```
Empty file directory
```
5.  open link  https://github.com/Qihoo360/wayne/tree/master/src/backend 
```
plugins @ 9d23dac
```

**Desktop (please complete the following information):**
 - OS: [10.14.1 ]
 - Browser [chrome]
- Go Version:- Go version:go1.11.1 darwin/amd64
- vscode

**Server Version**
```
- Wayne version:master
- Go version:go1.11.1 darwin/amd64
```

**Comment by motecshine** [comment]
git submodule update --init --recursive

**Comment by wilhelmguo** [comment]
@yulibaozi  refer  @motecshine reply.
